AWSTemplateFormatVersion: "2010-09-09"

Conditions:
  HasAcceptanceTests:
    Fn::Or:
      - Fn::Equals: [!Ref Environment, dev]
      - Fn::Equals: [!Ref Environment, build]
      - Fn::Equals: [!Ref Environment, staging]

Mappings:
  AcceptanceTestTags:
    dev:
      ui: >-
        @UI and not (@AccountInterventions or @Reauth or @old-mfa-without-ipv
        or @AccountRecovery or @InternationalSmsSendingDisabled
        or @PasskeyUsageEnabled) and not (@InternationalNumbersIndefiniteLockout
        and @under-development)
      api: >-
        @UI and not (@AccountInterventions or @Reauth or @old-mfa-without-ipv
        or @AccountRecovery or @InternationalSmsSendingDisabled
        or @PasskeyUsageEnabled) and not (@InternationalNumbersIndefiniteLockout
        and @under-development)
      am: >-
        @AccountManagementAPI and not (@AcceptInternationalNumbers)
    build:
      ui: >-
        @UI and not (@under-development or @AccountInterventions or @Reauth
        or @old-mfa-without-ipv or @AcceptInternationalNumbers
        or @InternationalSmsSendingDisabled or @PasskeysEnabled
        or @PasskeyUsageEnabled)
      api: >-
        @UI and not (@under-development or @AccountInterventions or @Reauth
        or @old-mfa-without-ipv or @AcceptInternationalNumbers
        or @InternationalSmsSendingDisabled or @PasskeysEnabled
        or @PasskeyUsageEnabled)
      am: >-
        @AccountManagementAPI and not (@under-development
        or @AcceptInternationalNumbers)
    staging:
      ui: >-
        @UI and not (@under-development or @AccountInterventions
        or @new-mfa-reset-with-ipv or @old-mfa-without-ipv
        or @AcceptInternationalNumbers or @InternationalSmsSendingDisabled
        or @SignInWithoutPasskeys or @PasskeyUsageEnabled
        or @EnvironmentWithAMCStubDeployed)
      api: >-
        @UI and not (@under-development or @AccountInterventions or @Reauth
        or @old-mfa-without-ipv or @new-mfa-reset-with-ipv
        or @AcceptInternationalNumbers or @InternationalSmsSendingDisabled
        or @SignInWithoutPasskeys or @PasskeyUsageEnabled
        or @EnvironmentWithAMCStubDeployed)
      am: >-
        @AccountManagementAPI and not (@under-development
        or @AcceptInternationalNumbers or @new-mfa-reset-with-ipv)

Resources:
  AcceptanceTestCucumberFilterTags:
    Type: AWS::SSM::Parameter
    Condition: HasAcceptanceTests
    Properties:
      Name: !Sub /acceptance-tests/${Environment}/CUCUMBER_FILTER_TAGS
      Type: String
      Value: !FindInMap
        - AcceptanceTestTags
        - !Ref Environment
        - ui
        - DefaultValue: "unused"

  AcceptanceTestAPICucumberFilterTags:
    Type: AWS::SSM::Parameter
    Condition: HasAcceptanceTests
    Properties:
      Name: !Sub /acceptance-tests/${Environment}/API_CUCUMBER_FILTER_TAGS
      Type: String
      Value: !FindInMap
        - AcceptanceTestTags
        - !Ref Environment
        - api
        - DefaultValue: "unused"

  AcceptanceTestAMCucumberFilterTags:
    Type: AWS::SSM::Parameter
    Condition: HasAcceptanceTests
    Properties:
      Name: !Sub /acceptance-tests/${Environment}/AM_CUCUMBER_FILTER_TAGS
      Type: String
      Value: !FindInMap
        - AcceptanceTestTags
        - !Ref Environment
        - am
        - DefaultValue: "unused"
