version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 3 1,15 * *"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 100
    ignore:
      - dependency-name: "gradle"
        versions: ["[9.0,)"]
      - dependency-name: "com.nimbusds:oauth2-oidc-sdk"
      - dependency-name: "org.junit*:*"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "org.mockito:*"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "org.hamcrest:*"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "org.wiremock:*"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "com.approvaltests:*"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "org.awaitility:*"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "uk.org.webcompere:*"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "au.com.dius.pact*:*"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "net.javacrumbs.json-unit:*"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "software.amazon.awssdk:*"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "com.amazonaws:*"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "aws.sdk.kotlin:*"
        update-types: ["version-update:semver-patch"]
    groups:
      dev-dependencies:
        patterns:
          - "org.junit*:*"
          - "org.mockito:*"
          - "org.hamcrest:*"
          - "org.wiremock:*"
          - "com.approvaltests:*"
          - "org.awaitility:*"
          - "uk.org.webcompere:*"
          - "au.com.dius.pact*:*"
          - "net.javacrumbs.json-unit:*"
      aws-dependencies:
        patterns:
          - "software.amazon.awssdk:*"
          - "com.amazonaws:*"
          - "aws.sdk.kotlin:*"
      gradle-security-updates:
        applies-to: security-updates
        update-types:
          - minor
          - patch
    target-branch: main
    commit-message:
      prefix: BAU

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 3 1,15 * *"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    groups:
      gha-all-dependencies:
        patterns:
          - "*"
    target-branch: main
    commit-message:
      prefix: BAU

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    groups:
      pip-all-dependencies:
        patterns:
          - "*"
    target-branch: main
    commit-message:
      prefix: BAU
    labels:
      - dependabot

  - package-ecosystem: pre-commit
    directory: "/"
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    target-branch: main
    commit-message:
      prefix: BAU
    labels:
      - dependabot
