package uk.gov.di.authentication.frontendapi.domain;

import uk.gov.di.authentication.shared.domain.AuditableEvent;

public enum FrontendAuditableEvent implements AuditableEvent {
    ACCOUNT_TEMPORARILY_LOCKED,
    INVALID_CREDENTIALS,
    NO_ACCOUNT_WITH_EMAIL,
    CODE_MAX_RETRIES_REACHED,
    CODE_VERIFIED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_SUCCESSFUL,
    LOG_IN_SUCCESS,
    CHECK_USER_INVALID_EMAIL,
    CHECK_USER_NO_ACCOUNT_WITH_EMAIL,
    CHECK_USER_KNOWN_EMAIL,
    CREATE_ACCOUNT_EMAIL_ALREADY_EXISTS,
    CREATE_ACCOUNT,
    CLIENT_INFO_FOUND,
    UPDATE_PROFILE_REQUEST_RECEIVED,
    UPDATE_PROFILE_REQUEST_ERROR,
    UPDATE_PROFILE_PHONE_NUMBER,
    UPDATE_PROFILE_CONSENT_UPDATED,
    UPDATE_PROFILE_TERMS_CONDS_ACCEPTANCE,
    MFA_INVALID_CODE_REQUEST,
    MFA_MISMATCHED_EMAIL,
    MFA_MISSING_PHONE_NUMBER,
    MFA_CODE_SENT,
    MFA_CODE_SENT_FOR_TEST_CLIENT
}
