repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 2c9f875913ee60ca25ce70243dc24d5b6415598c # v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: mixed-line-ending
      - id: check-executables-have-shebangs

  - repo: https://github.com/awslabs/cfn-python-lint
    rev: b16d6b4ce0796020a0ad5ee1c56453fde6079f2b # v1.9.3
    hooks:
      - id: cfn-python-lint
        exclude: ^(ci|.github|.sonarlint)/.*|docker-compose.*|.pre-commit-config.yaml|.*.approved.json|checkov-policies.*|.*/pacts/.*.json$

  - repo: local
    hooks:
      - id: gradle-spotless-apply
        name: Run Gradle Spotless Apply
        language: script
        entry: ./scripts/pre-commit__spotless-apply.sh
        types_or:
          - java
          - groovy
          - yaml
          - markdown
          - json
        pass_filenames: false
        require_serial: true

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: debe478691c6711d19679b9973309e19368e79b6 # v1.92.1
    hooks:
      - id: terraform_validate
        args:
          - --hook-config=--retry-once-with-cleanup=true
      - id: terraform_fmt

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 1ee2e387938ec90ec10a64f85fc0b4be527ade6a # v0.5.5
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format

  - repo: local
    hooks:
      - id: shfmt
        name: shfmt (shell scripts)
        language: golang
        additional_dependencies:
          - mvdan.cc/sh/v3/cmd/shfmt@v3.8.0
        entry: shfmt
        args: ["-w", "-s", "-l"]
        types:
          - file
          - shell
        exclude_types:
          - zsh
        exclude: ^gradlew$

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: a23f6b85d0fdd5bb9d564e2579e678033debbdff # v0.10.0.1
    hooks:
      - id: shellcheck
        exclude: ^gradlew$

  - repo: https://github.com/lalten/check-gha-pinning
    rev: 225deee5dff16fae532978007ce6e37045e14c68 # v1.3.0
    hooks:
      - id: check-gha-pinning
  - repo: https://github.com/rhysd/actionlint
    rev: 62dc61a45fc95efe8c800af7a557ab0b9165d63b # v1.7.1
    hooks:
      - id: actionlint
