version = 0.1
[dev.deploy.parameters]
stack_name = "authentication-api"
resolve_s3 = false
s3_bucket = "backend-pipeline-githubartifactsourcebucket-vljykfjnlde3"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "VpcStackName=\"vpc\" CodeSigningConfigArn=\"arn:aws:lambda:eu-west-2:975050272416:code-signing-config:csc-0a3c0dd11f680b73a\" PermissionsBoundary=\"arn:aws:iam::975050272416:policy/backend-pipeline-AppPermissionsBoundary-0ac7b09460c7\" Environment=\"dev\" SubEnvironment=\"none\" LambdaDeploymentPreference=\"AllAtOnce\" LoggingSubscriptionEndpointArn=\"arn:aws:logs:eu-west-2:885513274347:destination:csls_cw_logs_destination_prodpython-2\""
image_repositories = []
signing_profiles = "AuthTokenFunction=\"SigningProfile_bdzyxbYzrSD8\" AuthUserInfoFunction=\"SigningProfile_bdzyxbYzrSD8\" SecretString-JAVA_LAYER}}-cd3ae82ef4=\"SigningProfile_bdzyxbYzrSD8\""
