flowchart LR

    %% Systems
    account_management_api["Account Management API"]
    notify["Notify"]
    account_interventions["Account Interventions"]
    dynamodb["Dynamodb"]
    elasticache["Elasticache"]
    sqs["Sqs"]
    kms["Kms"]
    api_gateway["Api Gateway"]
    lambda["Lambda"]
    vpc["Vpc"]
    cloudwatch["Cloudwatch"]
    authentication_internal_api["Authentication Internal API"]
    ticf_cri["Ticf Cri"]

    %% Dependencies
    account_management_api --> notify
    account_management_api --> account_interventions
    account_management_api --> dynamodb
    account_management_api --> elasticache
    account_management_api --> sqs
    account_management_api --> kms
    account_management_api --> api_gateway
    account_management_api --> lambda
    account_management_api --> vpc
    account_management_api --> cloudwatch
    authentication_internal_api --> notify
    authentication_internal_api --> ticf_cri
    authentication_internal_api --> account_interventions
    authentication_internal_api --> dynamodb
    authentication_internal_api --> elasticache
    authentication_internal_api --> sqs
    authentication_internal_api --> kms
    authentication_internal_api --> api_gateway
    authentication_internal_api --> lambda
    authentication_internal_api --> vpc
    authentication_internal_api --> cloudwatch

    %% Styling