name: di-authentication-local

include:
  - ../docker-compose.yml

services:
  orchestration-stub:
    image: orch-stub-local:latest
    container_name: orch-stub-local
    build:
      context: ../../authentication-stubs/orchestration-stub
      dockerfile: Dockerfile
    env_file: ../../authentication-stubs/orchestration-stub/.env.local
    environment:
      AUTHENTICATION_BACKEND_URL: http://host.docker.internal:4402/
    ports:
      - "4400:4400"
    networks:
      - di-authentication-api-net

  authentication-frontend:
    image: authentication-frontend-local:latest
    container_name: authentication-frontend-local
    build:
      context: ../../authentication-frontend
      dockerfile: dev.Dockerfile
    env_file: ../../authentication-frontend/.env.local
    environment:
      FRONTEND_API_BASE_URL: http://host.docker.internal:4402/
    command: "node --enable-source-maps --inspect=0.0.0.0:5401 dist/server.js"
    ports:
      - "4401:4401"
      - "5401:5401"
    networks:
      - di-authentication-api-net

  authentication-api:
    image: authentication-api-local:latest
    container_name: authentication-api-local
    build:
      context: ../
      dockerfile: local-running/Dockerfile
    depends_on:
      aws:
        condition: service_healthy
      redis:
        condition: service_healthy
      dynamodb:
        condition: service_healthy
    env_file: ./.env.local
    environment:
      AUTHENTICATION_BACKEND_URI: http://host.docker.internal:4402/
      DYNAMO_ENDPOINT: http://host.docker.internal:8000
      LOCALSTACK_ENDPOINT: http://host.docker.internal:45678
      ORCHESTRATION_BACKEND_URI: http://host.docker.internal:4400/
      REDIS_HOST: host.docker.internal
      SQS_ENDPOINT: http://host.docker.internal:45678
    ports:
      - "4402:4402"
      - "5402:5402"
    networks:
      - di-authentication-api-net
