package uk.gov.di.authentication.shared.entity;

import uk.gov.di.authentication.shared.services.ConfigurationService;

public enum DeliveryReceiptsNotificationType implements TemplateAware {
    VERIFY_EMAIL("VERIFY_EMAIL", "VERIFY_EMAIL_TEMPLATE_ID"),
    RESET_PASSWORD("RESET_PASSWORD_EMAIL", "RESET_PASSWORD_TEMPLATE_ID"),
    PASSWORD_RESET_CONFIRMATION(
            "PASSWORD_RESET_CONFIRMATION_EMAIL", "PASSWORD_RESET_CONFIRMATION_TEMPLATE_ID"),
    PASSWORD_RESET_CONFIRMATION_SMS(
            "PASSWORD_RESET_CONFIRMATION_SMS", "PASSWORD_RESET_CONFIRMATION_SMS_TEMPLATE_ID"),
    ACCOUNT_CREATED_CONFIRMATION(
            "ACCOUNT_CREATED_CONFIRMATION_EMAIL", "ACCOUNT_CREATED_CONFIRMATION_TEMPLATE_ID"),
    RESET_PASSWORD_WITH_CODE(
            "RESET_PASSWORD_WITH_CODE_EMAIL", "RESET_PASSWORD_WITH_CODE_TEMPLATE_ID"),
    VERIFY_CHANGE_HOW_GET_SECURITY_CODES(
            "VERIFY_CHANGE_HOW_GET_SECURITY_CODES_EMAIL",
            "VERIFY_CHANGE_HOW_GET_SECURITY_CODES_TEMPLATE_ID"),
    CHANGE_HOW_GET_SECURITY_CODES_CONFIRMATION(
            "CHANGE_HOW_GET_SECURITY_CODES_CONFIRMATION_EMAIL",
            "CHANGE_HOW_GET_SECURITY_CODES_CONFIRMATION_TEMPLATE_ID"),
    EMAIL_UPDATED("EMAIL_UPDATED_EMAIL", "EMAIL_UPDATED_TEMPLATE_ID"),
    DELETE_ACCOUNT("DELETE_ACCOUNT_EMAIL", "DELETE_ACCOUNT_TEMPLATE_ID"),
    PHONE_NUMBER_UPDATED("PHONE_NUMBER_UPDATED_EMAIL", "PHONE_NUMBER_UPDATED_TEMPLATE_ID"),
    PASSWORD_UPDATED("PASSWORD_UPDATED_EMAIL", "PASSWORD_UPDATED_TEMPLATE_ID"),
    VERIFY_PHONE_NUMBER("VERIFY_PHONE_NUMBER_SMS", "VERIFY_PHONE_NUMBER_TEMPLATE_ID"),
    MFA_SMS("MFA_SMS", "MFA_SMS_TEMPLATE_ID"),
    AM_VERIFY_EMAIL("AM_VERIFY_EMAIL", "AM_VERIFY_EMAIL_TEMPLATE_ID"),
    AM_VERIFY_PHONE_NUMBER("AM_VERIFY_PHONE_NUMBER_SMS", "AM_VERIFY_PHONE_NUMBER_TEMPLATE_ID"),
    TERMS_AND_CONDITIONS_BULK_EMAIL(
            "TERMS_AND_CONDITIONS_BULK_EMAIL", "TERMS_AND_CONDITIONS_BULK_EMAIL_TEMPLATE_ID"),
    REPORT_SUSPICIOUS_ACTIVITY(
            "REPORT_SUSPICIOUS_ACTIVITY_EMAIL", "REPORT_SUSPICIOUS_ACTIVITY_EMAIL_TEMPLATE_ID"),
    BACKUP_METHOD_ADDED("BACKUP_METHOD_ADDED", "BACKUP_METHOD_ADDED_TEMPLATE_ID"),
    BACKUP_METHOD_REMOVED("BACKUP_METHOD_REMOVED", "BACKUP_METHOD_REMOVED_TEMPLATE_ID"),
    CHANGED_AUTHENTICATOR_APP("CHANGED_AUTHENTICATOR_APP", "CHANGED_AUTHENTICATOR_APP_TEMPLATE_ID"),
    CHANGED_DEFAULT_MFA("CHANGED_DEFAULT_MFA", "CHANGED_DEFAULT_MFA_TEMPLATE_ID"),
    SWITCHED_MFA_METHODS("SWITCHED_MFA_METHODS", "SWITCHED_MFA_METHODS_TEMPLATE_ID"),
    GLOBAL_LOGOUT("GLOBAL_LOGOUT", "GLOBAL_LOGOUT_TEMPLATE_ID");

    private final String templateAlias;
    private final String templateName;

    DeliveryReceiptsNotificationType(String templateAlias, String templateName) {
        this.templateAlias = templateAlias;
        this.templateName = templateName;
    }

    public String getTemplateName() {
        return templateName;
    }

    public String getTemplateId() {
        return System.getenv(templateName);
    }

    @Override
    public String getTemplateId(ConfigurationService configurationService) {
        return null;
    }

    public String getTemplateAlias() {
        return templateAlias;
    }
}
