package uk.gov.di.authentication.shared.entity;

public enum SessionAction {
    USER_CHOSE_TO_REGISTER_NEW_USER,
    USER_ENTERED_UNREGISTERED_EMAIL_ADDRESS,
    USER_ENTERED_REGISTERED_EMAIL_ADDRESS,
    USER_ENTERED_VALID_PASSWORD,
    USER_ENTERED_VALID_EMAIL_VERIFICATION_CODE,
    USER_ENTERED_INVALID_EMAIL_VERIFICATION_CODE,
    USER_ENTERED_INVALID_EMAIL_VERIFICATION_CODE_TOO_MANY_TIMES,
    USER_HAS_VALIDATED_EMAIL,
    USER_ENTERED_A_NEW_PHONE_NUMBER,
    SYSTEM_HAS_SENT_PHONE_VERIFICATION_CODE,
    USER_ENTERED_CORRECT_PHONE_VERIFICATION_CODE,
    USER_ENTERED_INCORRECT_PHONE_VERIFICATION_CODE,
    SYSTEM_HAS_ISSUED_AUTHORIZATION_CODE,
    USER_ENTERED_INCORRECT_PHONE_VERIFICATION_CODE_TOO_MANY_TIMES,
    USER_ENTERED_VALID_CREDENTIALS,
    SYSTEM_HAS_SENT_MFA_CODE,
    USER_ENTERED_VALID_MFA_CODE,
    USER_ENTERED_INVALID_MFA_CODE,
    USER_ENTERED_INVALID_MFA_CODE_TOO_MANY_TIMES
}
