package uk.gov.di.authentication.shared.entity;

public enum SessionState {
    NEW,
    USER_NOT_FOUND,
    AUTHENTICATION_REQUIRED,
    TWO_FACTOR_REQUIRED,
    VERIFY_EMAIL_CODE_SENT,
    VERIFY_PHONE_NUMBER_CODE_SENT,
    MFA_SMS_CODE_SENT,
    ADDED_UNVERIFIED_PHONE_NUMBER,
    ADDED_CONSENT,
    EMAIL_CODE_VERIFIED,
    EMAIL_CODE_NOT_VALID,
    EMAIL_CODE_MAX_RETRIES_REACHED,
    PHONE_NUMBER_CODE_NOT_VALID,
    PHONE_NUMBER_CODE_VERIFIED,
    PHONE_NUMBER_CODE_MAX_RETRIES_REACHED,
    MFA_CODE_MAX_RETRIES_REACHED,
    MFA_CODE_NOT_VALID,
    MFA_CODE_VERIFIED,
    LOGGED_IN,
    AUTHENTICATED,
    UPDATED_TERMS_AND_CONDITIONS,
    UPDATED_TERMS_AND_CONDITIONS_ACCEPTED,
    UPDATED_TERMS_AND_CONDITIONS_REJECTED
}
