AWSTemplateFormatVersion: "2010-09-09"
Description: Authentication DynamoDB tables for Client Data Storage

Parameters:
  Environment:
    Type: String
    Default: sandpit
    AllowedValues:
      - sandpit
      - build
      - integration
      - staging
      - production
    Description: The logical name for this deployment environment

Resources:
  ClientRegistry:
    # checkov:skip=CKV_AWS_119: "Ensure DynamoDB Tables are encrypted using a KMS Customer Managed CMK"
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: ClientID
          AttributeType: S
        - AttributeName: ClientName
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: ClientNameIndex
          KeySchema:
            - AttributeName: ClientName
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      KeySchema:
        - AttributeName: ClientID
          KeyType: HASH
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      TableName: !Sub "${Environment}-client-registry"
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: application
          Value: shared
