AWSTemplateFormatVersion: "2010-09-09"
Description: Authentication DynamoDB tables for Common Password Storage

Parameters:
  Environment:
    Type: String
    Default: sandpit
    AllowedValues:
      - sandpit
      - build
      - integration
      - staging
      - production
    Description: The logical name for this deployment environment

Resources:
  CommonPassword:
    # checkov:skip=CKV_AWS_119: "Ensure DynamoDB Tables are encrypted using a KMS Customer Managed CMK"
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: Password
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: Password
          KeyType: HASH
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      TableName: !Sub "${Environment}-common-passwords"
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: application
          Value: shared
