AWSTemplateFormatVersion: "2010-09-09"
Resources:
  UpdateEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub
        - ${Env}-update-email-lambda
        - Env: !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment]
      AutoPublishAlias: active
      ProvisionedConcurrencyConfig: !If
        - EnableProvisionedConcurrency
        - ProvisionedConcurrentExecutions:
            !FindInMap [
              EnvironmentConfiguration,
              !Ref Environment,
              lambdaMinConcurrency,
              DefaultValue: 0,
            ]
        - !Ref AWS::NoValue
      CodeUri: ./account-management-api/build/distributions/account-management-api.zip
      Handler: uk.gov.di.accountmanagement.lambda.UpdateEmailHandler::handleRequest
      Environment:
        Variables:
          REDIS_KEY: "account-management"
          ENVIRONMENT: !Sub
            - "${env}"
            - env:
                !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment]
          EMAIL_QUEUE_URL: !GetAtt EmailNotificationQueue.QueueUrl
          DYNAMO_ARN_PREFIX: !Sub
            - "arn:aws:dynamodb:${AWS::Region}:${DataStoreAccountId}:table/"
            - DataStoreAccountId:
                !FindInMap [
                  EnvironmentConfiguration,
                  !Ref Environment,
                  dataStoreAccountId,
                ]
          INTERNAl_SECTOR_URI: !If
            - IsNotProduction
            - !If
              - UseSubEnvironment
              - !Sub "https://identity.${SubEnvironment}.dev.account.gov.uk"
              - !Sub "https://identity.${Environment}.account.gov.uk"
            - "https://identity.account.gov.uk"
          TXMA_AUDIT_QUEUE_URL: !GetAtt AuthInternalApiTxMAAuditQueue.QueueUrl
      LoggingConfig:
        LogGroup: !Ref UpdateEmailFunctionLogGroup
      Policies:
        - !Ref LambdaBasicExecutionPolicy
        - !Ref DynamoUserReadAccessPolicy
        - !Ref DynamoUserReadWriteAccessPolicy
        - !Ref DynamoUserDeleteAccessPolicy
        - !Ref DynamoAuthSessionStoreReadAccessPolicy
        - !Ref DynamoEmailCheckResultReadAccessPolicy
        - !Ref AuditSigningKeyLambdaKmsSigningPolicy
        - !Ref RedisParametersAccessPolicy
        - !Ref AuthInternalApiTxMAAuditQueueAccessPolicy
        - !Ref UserProfileTableKmsPolicy
        - !Ref EmailCheckResultsTableKmsPolicy
        - !Ref AuditEventsSnsPolicy
      SnapStart:
        ApplyOn: None
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - Fn::ImportValue: !Sub ${VpcStackName}-PrivateSubnetIdA
          - Fn::ImportValue: !Sub ${VpcStackName}-PrivateSubnetIdB
          - Fn::ImportValue: !Sub ${VpcStackName}-PrivateSubnetIdC

  UpdateEmailFunctionAliasPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref UpdateEmailFunction.Alias
      Principal: apigateway.amazonaws.com

  UpdateEmailFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub
        - /aws/lambda/${Env}-update-email-lambda
        - Env: !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment]
      KmsKeyId: !GetAtt MainKmsKey.Arn
      RetentionInDays:
        !FindInMap [
          EnvironmentConfiguration,
          !Ref Environment,
          cloudwatchLogRetentionInDays,
        ]
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-UpdateEmailFunctionLogGroup"
        - Key: Environment
          Value: !Ref Environment
        - Key: Source
          Value: govuk-one-login/authentication-api/ci/cloudformation/account-management/function/update-email.yaml

  UpdateEmailFunctionErrorMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      FilterName: !Sub
        - ${Env}-update-email-errors
        - Env: !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment]
      FilterPattern: '{($.level = "ERROR")}'
      LogGroupName: !Ref UpdateEmailFunctionLogGroup
      MetricTransformations:
        - MetricName: !Sub
            - ${Env}-update-email-error-count
            - Env:
                !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment]
          MetricNamespace: LambdaErrorsNamespace
          MetricValue: 1

  UpdateEmailFunctionErrorCloudwatchAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions: !If
        - UseAlarmActions
        - - !Sub "{{resolve:ssm:/deploy/${Environment}/notification_topic_arn}}"
        - []
      AlarmDescription: !Sub
        - "${AlarmThreshold} or more number of errors have occurred in the ${Env}-update-email-lambda function. ${RunbookLink}"
        - AlarmThreshold:
            !FindInMap [
              EnvironmentConfiguration,
              !Ref Environment,
              lambdaLogAlarmThreshold,
              DefaultValue: 10,
            ]
          Env: !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment]
          RunbookLink:
            !FindInMap [
              LambdaConfiguration,
              "update-email",
              RunbookLink,
              DefaultValue: "",
            ]
      AlarmName: !Sub
        - ${Env}-update-email-alarm
        - Env: !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment]
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      MetricName: !Sub
        - ${Env}-update-email-error-count
        - Env: !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment]
      Namespace: LambdaErrorsNamespace
      Period: 3600
      Statistic: Sum
      Threshold:
        !FindInMap [
          EnvironmentConfiguration,
          !Ref Environment,
          lambdaLogAlarmThreshold,
          DefaultValue: 5,
        ]

  UpdateEmailFunctionSubscriptionFilter:
    Condition: IsSplunkEnabled
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      DestinationArn: !Ref LoggingSubscriptionEndpointArn
      FilterPattern: ""
      LogGroupName: !Ref UpdateEmailFunctionLogGroup
