---
openapi: 3.0.1
info:
  title:
    Fn::Sub: "${Environment}-di-auth-ext-api"
  version: "1.0.0"
paths:
  /token:
    post:
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AuthTokenFunction.Arn}:active/invocations
        passthroughBehavior: "when_no_match"
        timeoutInMillis: 29000
  /userinfo:
    get:
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AuthUserInfoFunction.Arn}:active/invocations
        passthroughBehavior: "when_no_match"
        timeoutInMillis: 29000
