---
openapi: 3.0.1
info:
  title: "AuthTokenRestApi"
  version: "1.0.0"
paths:
  /token:
    post:
      responses: {}
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AuthTokenFunction.Arn}:active/invocations
        passthroughBehavior: "when_no_match"
        type: "aws_proxy"
