package uk.gov.di.authentication.userpermissions.entity;

public enum ForbiddenReason {
    EXCEEDED_INCORRECT_EMAIL_ADDRESS_SUBMISSION_THRESHOLD,
    EXCEEDED_SEND_EMAIL_OTP_NOTIFICATION_THRESHOLD,
    EXCEEDED_INCORRECT_EMAIL_OTP_SUBMISSION_THRESHOLD,
    EXCEEDED_INCORRECT_PASSWORD_SUBMISSION_THRESHOLD,
    EXCEEDED_SEND_MFA_OTP_NOTIFICATION_THRESHOLD,
    EXCEEDED_INCORRECT_MFA_OTP_SUBMISSION_THRESHOLD,
}
