platform: linux
image_resource:
  type: registry-image
  source:
    repository: hashicorp/terraform
    tag: 1.1.9
    username: ((docker-hub-username))
    password: ((docker-hub-password))
params:
  DEPLOYER_ROLE_ARN: ((deployer-role-arn-non-prod))
  DEPLOY_ENVIRONMENT: build
  STATE_BUCKET: digital-identity-dev-tfstate
  STATE_LOCKING_TABLE: digital-identity-dev-tfstate-locking
  AUDIT_STORE_EXPIRY_DAYS: 7
  TXMA_OBFUSCATION_SECRET_ARN: ""
  TXMA_OBFUSCATION_SECRET_KMS_KEY_ARN: ""
inputs:
  - name: shared-terraform-outputs
  - name: api-terraform-src
  - name: audit-processors-release
outputs:
  - name: terraform-outputs
run:
  path: /bin/sh
  args:
    - -euc
    - |
      if [[ "${DEPLOY_ENVIRONMENT}" == "build" ]]; then
        ENABLE_STATE_LOCKING=true
      else
        ENABLE_STATE_LOCKING=false
      fi

      cd "api-terraform-src/ci/terraform/audit-processors"
      terraform init -input=false \
        -backend-config "role_arn=${DEPLOYER_ROLE_ARN}" \
        -backend-config "bucket=${STATE_BUCKET}" \
        -backend-config "key=${DEPLOY_ENVIRONMENT}-audit-terraform.tfstate" \
        -backend-config "encrypt=true" \
        -backend-config "region=eu-west-2" \
        -backend-config "dynamodb_table=${STATE_LOCKING_TABLE}"

      terraform apply -auto-approve \
        -var "lambda_zip_file=$(ls -1 ../../../../audit-processors-release/*.zip)" \
        -var "deployer_role_arn=${DEPLOYER_ROLE_ARN}" \
        -var "environment=${DEPLOY_ENVIRONMENT}" \
        -var "shared_state_bucket=${STATE_BUCKET}" \
        -var "audit_storage_expiry_days=${AUDIT_STORE_EXPIRY_DAYS}" \
        -var "txma_obfuscation_secret_arn=${TXMA_OBFUSCATION_SECRET_ARN}" \
        -var "txma_obfuscation_secret_kms_key_arn=${TXMA_OBFUSCATION_SECRET_KMS_KEY_ARN}" \
        -var-file "${DEPLOY_ENVIRONMENT}-overrides.tfvars" \
        -lock="${ENABLE_STATE_LOCKING}"

      terraform output --json > ../../../../terraform-outputs/${DEPLOY_ENVIRONMENT}-terraform-outputs.json
