openapi: "3.0.1"

info:
  title: "account-data-api"
  version: 0.0.3
  description: Account Data API

paths:
  /accounts/{publicSubjectId}/authenticators/passkeys:
    parameters:
      - name: publicSubjectId
        in: path
        description: Public subject ID
        required: true
        schema:
          type: string
    get:
      summary: Read all passkeys belonging to a user
      responses:
        "200":
          description: List of passkeys
          content:
            application/json:
              schema:
                type: object
                properties:
                  passkeys:
                    type: array
                    items:
                      $ref: "#/components/schemas/PasskeyAuthenticator"

components:
  schemas:
    PasskeyAuthenticator:
      type: object
      properties:
        id:
          type: string
          example: "7f3a94c4-3079-451b-956d-d8351dca9420"
        type:
          type: string
          example: "passkey"
        name:
          type: string
          example: "My passkey"
