---
openapi: 3.0.1
info:
  title: "Authentication Internal API"
  version: "1.0.0"
paths:
  /account-interventions:
    post:
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AccountInterventionsFunction.Arn}:active/invocations
        passthroughBehavior: "when_no_match"
        timeoutInMillis: 29000
  /account-recovery:
    post:
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AccountRecoveryFunction.Arn}:active/invocations
        passthroughBehavior: "when_no_match"
        timeoutInMillis: 29000
  /check-email-fraud-block:
    post:
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CheckEmailFraudBlockFunction.Arn}:active/invocations
        passthroughBehavior: "when_no_match"
        timeoutInMillis: 29000
  /check-reauth-user:
    post:
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CheckReAuthUserFunction.Arn}:active/invocations
        passthroughBehavior: "when_no_match"
        timeoutInMillis: 29000
  /id-reverification-state:
    post:
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${IDReverificationStateFunction.Arn}:active/invocations
        passthroughBehavior: "when_no_match"
        timeoutInMillis: 29000
  /login:
    post:
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LoginFunction.Arn}:active/invocations
        passthroughBehavior: "when_no_match"
        timeoutInMillis: 29000
  /mfa:
    post:
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MfaFunction.Arn}:active/invocations
        passthroughBehavior: "when_no_match"
        timeoutInMillis: 29000
  /mfa-reset-authorize:
    post:
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MfaResetAuthorizeFunction.Arn}:active/invocations
        passthroughBehavior: "when_no_match"
        timeoutInMillis: 29000
  /orch-auth-code:
    post:
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OrchAuthCodeFunction.Arn}:active/invocations
        passthroughBehavior: "when_no_match"
        timeoutInMillis: 29000
  /reset-password:
    post:
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ResetPasswordFunction.Arn}:active/invocations
        passthroughBehavior: "when_no_match"
        timeoutInMillis: 29000
  /reset-password-request:
    post:
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ResetPasswordRequestFunction.Arn}:active/invocations
        passthroughBehavior: "when_no_match"
        timeoutInMillis: 29000
  /reverification-result:
    post:
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ReverificationResultFunction.Arn}:active/invocations
        passthroughBehavior: "when_no_match"
        timeoutInMillis: 29000
  /send-notification:
    post:
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SendNotificationFunction.Arn}:active/invocations
        passthroughBehavior: "when_no_match"
        timeoutInMillis: 29000
  /signup:
    post:
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SignUpFunction.Arn}:active/invocations
        passthroughBehavior: "when_no_match"
        timeoutInMillis: 29000
  /start:
    post:
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${StartFunction.Arn}:active/invocations
        passthroughBehavior: "when_no_match"
        timeoutInMillis: 29000
  /update-profile:
    post:
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UpdateProfileFunction.Arn}:active/invocations
        passthroughBehavior: "when_no_match"
        timeoutInMillis: 29000
  /user-exists:
    post:
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UserExistsFunction.Arn}:active/invocations
        passthroughBehavior: "when_no_match"
        timeoutInMillis: 29000
  /verify-code:
    post:
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${VerifyCodeFunction.Arn}:active/invocations
        passthroughBehavior: "when_no_match"
        timeoutInMillis: 29000
  /verify-mfa-code:
    post:
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${VerifyMfaCodeFunction.Arn}:active/invocations
        passthroughBehavior: "when_no_match"
        timeoutInMillis: 29000
