sequenceDiagram
    participant rp as Relying Party
    participant orch_api as Orchestration OIDC API
    participant dcmaw as DCMAW
    rp ->> orch_api : OIDC Authentication request to /authorize via browser (AuthorisationHandler.java)
    orch_api  ->> orch_api : Validates Authentication request, creates session cookie
    orch_api ->> orch_api : Generates a signed and encrypted OAuth 2.0 Authorization request
    orch_api ->> dcmaw : Redirect to /authorize via browser
    dcmaw ->> orch_api : Authorisation response via browser to /doc-app-callback (DocAppCallbackHandler.java)
    orch_api ->> dcmaw : Token request containing Authorization code to /token
    dcmaw ->> orch_api : Token response containing access token
    orch_api ->> dcmaw : Userinfo request containing access token to /userinfo (UserInfoHandler.java)
    dcmaw ->> orch_api : Userinfo response containing Doc App Credential
    orch_api ->> orch_api : Saves Doc App Credential to Dynamo with a 3 min TTL
    orch_api ->> orch_api : Generates and store Authorization Code with 5 min TTL
    orch_api ->> rp : 302 redirect containing Authentication Response to the RPs redirect URL
    rp ->> orch_api : Token request to /token (TokenHandler.java)
    orch_api ->> orch_api : Validates token request, then generates and stores access token with 3 min TTL
    orch_api ->> rp : Token response containing access and id token 
    rp ->> orch_api : UserInfo request to /userinfo (UserInfoHandler.java)
    orch_api ->> orch_api : Validates Access Token
    orch_api ->> rp : UserInfo response containing doc app credential
