# Please read guidance on confluence before use
# (https://govukverify.atlassian.net/wiki/spaces/LO/pages/4606132332/Manually+Testing+Account+Management+API).
# Populate the authToken value below use (using scripts/generate-auth-token.sh)

@authToken = unset
@publicSubjectId = unset
@mfaIdentifier = unset

### Post to /authenticate
POST {{baseUrl}}/authenticate
Authorization:Bearer {{authToken}}

{
"email": "your.email@digital.cabinet-office.gov.uk",
"password": "currentPassword123!"
}

### Post to /send-otp-notification
# You must make a successful request to this endpoint to receive an otp to put into requests for /update-email
# and /update-phone-number.
# notificationType must be "VERIFY_EMAIL" or "VERIFY_PHONE_NUMBER", depending desired type of OTP and subsequent
# endpoint you want to make a request to.
# The email or phoneNumber field must be populated with a new value if looking to update email or phone number.
POST {{baseUrl}}/send-otp-notification
Authorization:Bearer {{authToken}}

{
"notificationType": "{ VERIFY_PHONE_NUMBER or VERIFY_EMAIL }",
"email": "your.email@digital.cabinet-office.gov.uk",
"phoneNumber": "07xxxxxxxxx"
}

### Post to /update-email
# REQUIRES CLIENT REGISTRY CHANGE - CHANGE BACK AFTER USE
POST {{baseUrl}}/update-email
Authorization:Bearer {{authToken}}

{
"existingEmailAddress": "your.email@digital.cabinet-office.gov.uk",
"replacementEmailAddress": "new_email_registered.with_notify@digital.cabinet-office.gov.uk",
"otp": "111111"
}

### Post to /delete-account
# REQUIRES CLIENT REGISTRY CHANGE - CHANGE BACK AFTER USE
POST {{baseUrl}}/delete-account
Authorization:Bearer {{authToken}}

{
"email": "your.email@digital.cabinet-office.gov.uk"
}

### Post to /update-password
# REQUIRES CLIENT REGISTRY CHANGE - CHANGE BACK AFTER USE
POST {{baseUrl}}/update-password
Authorization:Bearer {{authToken}}

{
"email": "your.email@digital.cabinet-office.gov.uk",
"newPassword": "newPassword123!"
}

### Post to /update-phone-number
# REQUIRES CLIENT REGISTRY CHANGE - CHANGE BACK AFTER USE
# After updating a phone number, when receiving an OTP going through a sign in journey immediately after, the check
# your phone screen will display the old phone number digits. This does not happen in the real service.
POST {{baseUrl}}/update-phone-number
Authorization:Bearer {{authToken}}

{
"email": "your.email@digital.cabinet-office.gov.uk",
"phoneNumber": "{ new phone number }",
"otp": "111111"
}

### Get to /v1/mfa-methods/{publicSubjectId}
# Gets a user's MFA methods
# Must populate publicSubjectId for a specified environment, getting the value from User Profile table for your email
# Must also run ./scripts/api-proxy.sh account-management [environment]
GET http://localhost:8123/v1/mfa-methods/{{publicSubjectId}}
Authorization:Bearer {{authToken}}

### Post to /v1/mfa-methods/{publicSubjectId}
# Creates a new MFA method (must be back up to be successful)
# Must populate publicSubjectId for a specified environment, getting the value from User Profile table for your email
# Must also run ./scripts/api-proxy.sh account-management [environment]
POST http://localhost:8123/v1/mfa-methods/{{publicSubjectId}}
Authorization:Bearer {{authToken}}

{
"mfaMethod": {
"priorityIdentifier": "BACKUP",
"method": {
"mfaMethodType": "{ AUTH_APP or SMS }",
"{ credential or phoneNumber }": "{ credential or phoneNumber }"
}
}
}

### Delete to /v1/mfa-methods/{publicSubjectId}/{mfaIdentifier}
# Deletes a user's MFA method (must be backup)
# Must populate publicSubjectId for a specified environment, getting the value from User Profile table for your email
# Must first get mfaIdentifier of the mfa method you want to change by using get to /v1/mfa-methods/{publicSubjectId} populating mfaIdentifier field
# Must also run ./scripts/api-proxy.sh account-management [environment]
DELETE http://localhost:8123/v1/mfa-methods/{{publicSubjectId}}/{{mfaIdentifier}}
Authorization:Bearer {{authToken}}

### Put to /v1/mfa-methods/{publicSubjectId}/{mfaIdentifier}
# Updates a user's MFA method (must be backup)
# Must populate publicSubjectId for a specified environment, getting the value from User Profile table for your email
# Must first get mfaIdentifier of the mfa method you want to change by using get to /v1/mfa-methods/{publicSubjectId} populating mfaIdentifier field
# Must also run ./scripts/api-proxy.sh account-management [environment]
PUT http://localhost:8123/v1/mfa-methods/{{publicSubjectId}}/{{mfaIdentifier}}
Authorization:Bearer {{authToken}}

{
"mfaMethod": {
"priorityIdentifier": "BACKUP",
"method": {
"mfaMethodType": "{ AUTH_APP or SMS }",
"{ credential or phoneNumber }": "{ credential or phoneNumber }"
}
}
}
