sequenceDiagram
    participant orch_api as Orchestration
    participant auth_frontend as Authentication Frontend
    participant auth_external_api as Authentication External API
    participant auth_internal_api as Authentication Internal API 
    participant account_interventions as Account Interventions API   
    orch_api ->> auth_frontend : OAuth 2.0 Authorization request 302 redirect to /authorize
    auth_frontend ->> auth_frontend : Decrypt and validate request and create session    
    auth_frontend ->> auth_internal_api : Request to /start (StartHandler.java)
    auth_internal_api ->> auth_internal_api : Start helps calculate current state
    auth_internal_api ->> auth_frontend : StartResponse.java object returned
    auth_frontend ->> auth_frontend : State machine works out where to send user based on start response
    auth_frontend ->> auth_internal_api : Request to /user-exists (CheckUserExistsHandler.java)
    auth_internal_api ->> auth_internal_api : Checks if account with email already exists
    auth_internal_api ->> auth_frontend: CheckUserExistsResponse.java object returned
    auth_frontend ->> auth_frontend: Validates that the user already has an account
    auth_frontend ->> auth_internal_api : Request to /account-interventions (AccountInterventionsHandler.java)
    auth_internal_api ->> account_interventions : Request to account interventions api (AccountInterventionsRequest.java)
    account_interventions ->> auth_internal_api : Response from Account Interventions containing blocked=true
    auth_internal_api ->> auth_internal_api : Generates audit event for "blocked" Account Intervention
    auth_internal_api ->> auth_frontend: AccountInterventions.java object returned containing blocked intervention
    auth_frontend ->> auth_frontend: Prevents user from performing password reset due to blocked intervention
    auth_frontend ->> auth_internal_api : Request to /login (LoginHandler.java)
    auth_internal_api ->> auth_internal_api : Validates if password is correct
    auth_internal_api ->> auth_frontend: LoginResponse.java object returned
    auth_frontend ->> auth_internal_api : Request to /account-recovery (AccountRecoveryHandler.java)
    auth_internal_api ->> auth_internal_api : Calculates whether account recovery is permitted
    auth_internal_api ->> auth_frontend: AccountRecovery.java object returned
    auth_frontend ->> auth_frontend: Prevents user from performing MFA reset due to blocked intervention
    auth_frontend ->> auth_internal_api : Request to /verify-mfa-code (VerifyMfaCodeHandler.java)
    auth_internal_api ->> auth_internal_api : Validates whether Auth App MFA code is valid
    auth_internal_api ->> auth_frontend: 204 response 
    auth_frontend ->> auth_frontend : Displays Blocked intervention screen