openapi: 3.0.3
info:
  title: Method Management API
  description: Method Management API
  version: 0.0.2
servers:
  - url: 'https://localhost:63342'
paths:
  /get-mfa-methods:
    post:
      tags:
        - 2FAManagement
      summary: Retrieves the list of MFA Methods for a user
      operationId: "get-mfa-methods"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MfaListRequest'
        required: true
      responses:
        '200':
          description: Successful Operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MfaMethodList'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
  /mfa-method:
    put:
      tags:
        - 2FAManagement
      summary: Creates an mfa method, or updates an mfa method if an mfa identifier is passed. If the new MFA method created is 'PRIMARY', the current 'PRIMARY' gets relegated to secondary.
      operationId: "mfa-method"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MfaMethodCreateOrUpdateRequest'
      responses:
        '201':
          description: MFA Method Created
        '202':
          description: MFA Method Updated
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
    delete:
      tags:
        - 2FAManagement
      summary: Deletes the mfa method identified by the mfa identifier. Cannot delete an identifier that is 'PRIMARY'.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MfaMethodDeleteReq'
      responses:
        '200':
          description: MFA Method Deleted
        '404':
          description: MFA Method Not found
        '412':
          description: Cannot delete a Primary Mfa Method
  /mfa-method-priority:
    post:
      tags:
        - 2FAManagement
      summary: Sets the priority for a given mfa method (Primary, secondary). Setting a method to 'PRIMARY' relegates the existing Primary to Secondary.
      operationId: "mfa-method-priority"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MethodPriorityChangeReq'
      responses:
        '200':
          description: Successful Operation
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '404':
          description: MFA Method not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
components:
  schemas:
    MfaMethod:
      type: object
      properties:
        mfaIdentifier:
          type: integer
        priorityIdentifier:
          type: string
          enum:
            - PRIMARY
            - SECONDARY
        mfaMethodType:
          type: string
          enum:
            - SMS
            - AUTH_APP
        endPoint:
          type: string
        methodVerified:
          type: boolean
    MfaListRequest:
      required:
        - email
      type: object
      properties:
        email:
          type: string
    MfaMethodList:
      type: array
      items:
        $ref: '#/components/schemas/MfaMethod'
    MfaMethodCreateOrUpdateRequest:
      required:
        - email
        - mfaIdentifier
        - mfaMethodType
        - priorityIdentifier
        - endpoint
        - credential
        - otp
      type: object
      properties:
        email:
          type: string
        mfaIdentifier:
          type: string
        priorityIdentifier:
          type: string
          enum:
            - PRIMARY
            - SECONDARY
        mfaMethodType:
          type: string
          enum:
            - SMS
            - AUTH_APP
        endpoint:
          type: string
        credential:
          type: string
        otp:
          type: string
    MethodPriorityChangeReq:
      required:
        - email
        - mfaIdentifier
        - updatedPriorityIdentifier
      type: object
      properties:
        email:
          type: string
        mfaIdentifier:
          type: integer
        updatedPriorityIdentifier:
          type: string
          enum:
            - PRIMARY
            - SECONDARY
    MfaMethodDeleteReq:
      required:
        - email
        - mfaIdentifier
      type: object
      properties:
        email:
          type: string
        mfaIdentifier:
          type: integer
    ErrorDetails:
      type: object
      properties:
        errorCode:
          type: string
        errorMessage:
          type: string