Resources:
  BulkUserEmailAudienceLoaderLambda:
    Type: AWS::Serverless::Function
    Condition: BulkEmailSendingEnabled
    Properties:
      FunctionName: !Sub
        - "${EnvironmentName}-bulk-user-email-audience-loader-lambda"
        - EnvironmentName:
            !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment]
      CodeUri: ./utils/build/distributions/utils.zip
      Handler: uk.gov.di.authentication.utils.lambda.BulkUserEmailAudienceLoaderHandler::handleRequest
      Policies:
        - !Ref LambdaBasicExecutionPolicy
        - !Ref DynamoUserReadAccessPolicy
        - !Ref DynamoCredentialReadAccessPolicy
        - !Ref DynamoBulkEmailTablesAccessPolicy
        - !Ref EmailCheckResultsTableKmsAccessPolicy
        - !Ref CloudWatchLogsKmsAccessPolicy
      AutoPublishAlias: live
      LoggingConfig:
        LogGroup: !Ref BulkUserEmailAudienceLoaderLogGroup
      Environment:
        Variables:
          DYNAMO_ARN_PREFIX: !Sub
            - "arn:aws:dynamodb:${AWS::Region}:${DataStoreAccountId}:table/"
            - DataStoreAccountId:
                !FindInMap [
                  EnvironmentConfiguration,
                  !Ref Environment,
                  dataStoreAccountId,
                ]
          ENVIRONMENT:
            !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment]
          BULK_USER_EMAIL_MAX_AUDIENCE_LOAD_USER_COUNT: !If
            - UseSubEnvironment
            - !FindInMap [
                EnvironmentConfiguration,
                !Ref SubEnvironment,
                bulkEmailMaxAudienceLoadUserCount,
              ]
            - !FindInMap [
                EnvironmentConfiguration,
                !Ref Environment,
                bulkEmailMaxAudienceLoadUserCount,
              ]
          BULK_USER_EMAIL_MAX_AUDIENCE_LOAD_USER_BATCH_SIZE: !If
            - UseSubEnvironment
            - !FindInMap [
                EnvironmentConfiguration,
                !Ref SubEnvironment,
                bulkEmailMaxAudienceLoadUserBatchSize,
              ]
            - !FindInMap [
                EnvironmentConfiguration,
                !Ref Environment,
                bulkEmailMaxAudienceLoadUserBatchSize,
              ]
          BULK_USER_EMAIL_INCLUDED_TERMS_AND_CONDITIONS: !If
            - UseSubEnvironment
            - !FindInMap [
                EnvironmentConfiguration,
                !Ref SubEnvironment,
                bulkEmailIncludedTermsAndConditions,
              ]
            - !FindInMap [
                EnvironmentConfiguration,
                !Ref Environment,
                bulkEmailIncludedTermsAndConditions,
              ]
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: !If
              - UseSubEnvironment
              - !FindInMap [
                  EnvironmentConfiguration,
                  !Ref SubEnvironment,
                  bulkEmailAudienceLoaderScheduleExpression,
                ]
              - !FindInMap [
                  EnvironmentConfiguration,
                  !Ref Environment,
                  bulkEmailAudienceLoaderScheduleExpression,
                ]
            Description: Triggers bulk user email audience loader Lambda on schedule
            Enabled: !Equals
              - !If
                - UseSubEnvironment
                - !FindInMap [
                    EnvironmentConfiguration,
                    !Ref SubEnvironment,
                    bulkEmailAudienceLoaderScheduleState,
                  ]
                - !FindInMap [
                    EnvironmentConfiguration,
                    !Ref Environment,
                    bulkEmailAudienceLoaderScheduleState,
                  ]
              - ENABLED
      Tags:
        Name: !Sub
          - "${EnvironmentName}-bulk-user-email-audience-loader-lambda"
          - EnvironmentName:
              !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment]
        Environment:
          !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment]

  BulkUserEmailAudienceLoaderLogGroup:
    Type: AWS::Logs::LogGroup
    Condition: BulkEmailSendingEnabled
    Properties:
      LogGroupName: !Sub
        - "/aws/lambda/${EnvironmentName}-bulk-user-email-audience-loader-lambda"
        - EnvironmentName:
            !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment]
      RetentionInDays: !If
        - UseSubEnvironment
        - !FindInMap [
            EnvironmentConfiguration,
            !Ref SubEnvironment,
            logRetentionDays,
          ]
        - !FindInMap [
            EnvironmentConfiguration,
            !Ref Environment,
            logRetentionDays,
          ]
      KmsKeyId: !GetAtt MainKmsKey.Arn

  BulkUserEmailAudienceLoaderLogSubscription:
    Type: AWS::Logs::SubscriptionFilter
    Condition: BulkEmailSendingEnabledAndSplunkEnabled
    Properties:
      LogGroupName: !Ref BulkUserEmailAudienceLoaderLogGroup
      FilterPattern: ""
      DestinationArn: !Ref LoggingSubscriptionEndpointArn

  BulkUserEmailAudienceLoaderErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: BulkEmailSendingEnabledAndUseAlarmActions
    Properties:
      AlarmName: !Sub
        - "${EnvironmentName}-bulk-user-email-audience-loader-lambda-errors"
        - EnvironmentName:
            !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment]
      AlarmDescription: Triggers when bulk user email audience loader Lambda error rate exceeds threshold
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 900
      EvaluationPeriods: 1
      Threshold: !If
        - UseSubEnvironment
        - !FindInMap [
            EnvironmentConfiguration,
            !Ref SubEnvironment,
            lambdaErrorThreshold,
          ]
        - !FindInMap [
            EnvironmentConfiguration,
            !Ref Environment,
            lambdaErrorThreshold,
          ]
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref BulkUserEmailAudienceLoaderLambda
      TreatMissingData: notBreaching
