Resources:
  DeleteSyntheticsUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub
        - "${EnvironmentName}-test-services-delete-synthetics-user"
        - EnvironmentName: !If
            - UseSubEnvironment
            - !Ref SubEnvironment
            - !Ref Environment
      CodeUri: ./test-services-api/build/distributions/test-services-api.zip
      Handler: uk.gov.di.authentication.testservices.lambda.DeleteSyntheticsUserHandler::handleRequest
      Environment:
        Variables:
          ENVIRONMENT:
            !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment]
          SYNTHETICS_USERS: simulate-delivered@notifications.service.gov.uk
          DYNAMO_ARN_PREFIX: !Sub
            - "arn:aws:dynamodb:${AWS::Region}:${DataStoreAccountId}:table/"
            - DataStoreAccountId:
                !FindInMap [
                  EnvironmentConfiguration,
                  !Ref Environment,
                  dataStoreAccountId,
                ]
      Policies:
        - !Ref LambdaBasicExecutionPolicy
        - !Ref DynamoUserReadWriteAccessPolicy
        - !Ref DynamoCredentialReadWriteAccessPolicy
        - !Ref TestServicesApiTxMAAuditQueueAccessPolicy
        - !Ref DynamoUserDeleteAccessPolicy
      AutoPublishAlias: active
      LoggingConfig:
        LogGroup: !Ref DeleteSyntheticsUserLogGroup
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - Fn::ImportValue: !Sub "${VpcStackName}-PrivateSubnetIdA"
          - Fn::ImportValue: !Sub "${VpcStackName}-PrivateSubnetIdB"
      Tags:
        Name: !Sub
          - "${EnvironmentName}-test-services-delete-synthetics-user"
          - EnvironmentName: !If
              - UseSubEnvironment
              - !Ref SubEnvironment
              - !Ref Environment
        Environment: !If
          - UseSubEnvironment
          - !Ref SubEnvironment
          - !Ref Environment

  DeleteSyntheticsUserLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub
        - "/aws/lambda/${EnvironmentName}-test-services-delete-synthetics-user"
        - EnvironmentName: !If
            - UseSubEnvironment
            - !Ref SubEnvironment
            - !Ref Environment
      RetentionInDays: !If
        - UseSubEnvironment
        - !FindInMap [
            EnvironmentConfiguration,
            !Ref SubEnvironment,
            logRetentionDays,
          ]
        - !FindInMap [
            EnvironmentConfiguration,
            !Ref Environment,
            logRetentionDays,
          ]
      KmsKeyId: !GetAtt MainKmsKey.Arn

  DeleteSyntheticsUserLogSubscription:
    Type: AWS::Logs::SubscriptionFilter
    Condition: IsSplunkEnabled
    Properties:
      LogGroupName: !Ref DeleteSyntheticsUserLogGroup
      FilterPattern: ""
      DestinationArn: !Ref LoggingSubscriptionEndpointArn

  DeleteSyntheticsUserErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: UseAlarmActions
    Properties:
      AlarmName: !Sub
        - "${EnvironmentName}-test-services-delete-synthetics-user-errors"
        - EnvironmentName: !If
            - UseSubEnvironment
            - !Ref SubEnvironment
            - !Ref Environment
      AlarmDescription: Triggers when MFA method analysis Lambda error rate exceeds threshold
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 900
      EvaluationPeriods: 1
      Threshold: !If
        - UseSubEnvironment
        - !FindInMap [
            EnvironmentConfiguration,
            !Ref SubEnvironment,
            lambdaErrorThreshold,
          ]
        - !FindInMap [
            EnvironmentConfiguration,
            !Ref Environment,
            lambdaErrorThreshold,
          ]
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref DeleteSyntheticsUserFunction
      TreatMissingData: notBreaching
