Resources:
  InactiveAccountDataExportLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub
        - "${EnvironmentName}-inactive-account-data-export-lambda"
        - EnvironmentName:
            !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment]
      CodeUri: ./utils/build/distributions/utils.zip
      Handler: uk.gov.di.authentication.utils.lambda.InactiveAccountDataExportHandler::handleRequest
      ReservedConcurrentExecutions: 1
      Environment:
        Variables:
          ENVIRONMENT:
            !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment]
          DYNAMO_ARN_PREFIX: !Sub
            - "arn:aws:dynamodb:${AWS::Region}:${DataStoreAccountId}:table/"
            - DataStoreAccountId:
                !FindInMap [
                  EnvironmentConfiguration,
                  !Ref Environment,
                  dataStoreAccountId,
                ]
      Policies:
        - !Ref LambdaBasicExecutionPolicy
        - !Ref DynamoUserReadAccessPolicy
        - !Ref DynamoCredentialReadAccessPolicy
        - !Ref CloudWatchLogsKmsAccessPolicy
      AutoPublishAlias: live
      LoggingConfig:
        LogGroup: !Ref InactiveAccountDataExportLogGroup
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - Fn::ImportValue: !Sub "${VpcStackName}-PrivateSubnetIdA"
          - Fn::ImportValue: !Sub "${VpcStackName}-PrivateSubnetIdB"
      Tags:
        Name: !Sub
          - "${EnvironmentName}-inactive-account-data-export-lambda"
          - EnvironmentName:
              !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment]
        Environment:
          !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment]

  InactiveAccountDataExportLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub
        - "/aws/lambda/${EnvironmentName}-inactive-account-data-export-lambda"
        - EnvironmentName:
            !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment]
      RetentionInDays: !If
        - UseSubEnvironment
        - !FindInMap [
            EnvironmentConfiguration,
            !Ref SubEnvironment,
            logRetentionDays,
          ]
        - !FindInMap [
            EnvironmentConfiguration,
            !Ref Environment,
            logRetentionDays,
          ]
      KmsKeyId: !GetAtt MainKmsKey.Arn

  InactiveAccountDataExportLogSubscription:
    Type: AWS::Logs::SubscriptionFilter
    Condition: IsSplunkEnabled
    Properties:
      LogGroupName: !Ref InactiveAccountDataExportLogGroup
      FilterPattern: ""
      DestinationArn: !Ref LoggingSubscriptionEndpointArn
