sequenceDiagram
    participant rp as Relying Party
    participant orch_api as Orchestration OIDC API
    participant auth as Authentication
    participant ais as AIS
    rp ->> orch_api : OIDC Authentication request to /authorize via browser (AuthorisationHandler.java)
    orch_api  ->> orch_api : Validates Authentication request, creates session cookie
    orch_api ->> orch_api : Generates a signed and encrypted OAuth 2.0 Authorization request
    orch_api ->> auth : OAuth 2.0 Authorization request to /authorize via browser
    auth ->> auth : Authenticates the user
    auth ->> orch_api : Authorisation response via browser to /orchestration-redirect (AuthenticationCallbackHandler.java)
    orch_api ->> auth : Token request containing Authorization code to /token
    auth ->> orch_api : Token response containing access token
    orch_api ->> auth : Userinfo request containing access token to /userinfo (UserInfoHandler.java)
    auth ->> orch_api : Userinfo response
    orch_api -->> ais : Check for interventions
    orch_api ->> orch_api : Generates and store Authorization Code with 5 min TTL
    orch_api ->> rp : 302 redirect containing Authentication Response to the RPs redirect URL
    rp ->> orch_api : Token request to /token (TokenHandler.java)
    orch_api ->> orch_api : Validates token request, then generates and stores access token with 3 min TTL
    orch_api ->> rp : Token response containing access and id tokens
    rp ->> orch_api : UserInfo request to /userinfo (UserInfoHandler.java)
    orch_api ->> orch_api : Validates Access Token
    orch_api ->> rp : UserInfo response containing user information
