package uk.gov.di.entity;

public enum SessionState {
    NEW,
    USER_NOT_FOUND,
    AUTHENTICATION_REQUIRED,
    TWO_FACTOR_REQUIRED,
    VERIFY_EMAIL_CODE_SENT,
    VERIFY_PHONE_NUMBER_CODE_SENT,
    ADDED_UNVERIFIED_PHONE_NUMBER,
    EMAIL_CODE_VERIFIED,
    EMAIL_CODE_NOT_VALID,
    PHONE_NUMBER_CODE_NOT_VALID,
    PHONE_NUMBER_CODE_VERIFIED,
    AUTHENTICATED
}
