version = 0.1
[dev.deploy.parameters]
stack_name = "authentication-api"
resolve_s3 = false
s3_bucket = "authentication-api-pipeli-githubartifactsourcebuck-nrimyerwstuw"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "VpcStackName=\"vpc\" CodeSigningConfigArn=\"arn:aws:lambda:eu-west-2:975050272416:code-signing-config:csc-006e0d5d35d5a5545\" PermissionsBoundary=\"arn:aws:iam::975050272416:policy/authentication-api-pipeline-AppProgrammaticPermissionsBoundary-06d1005edc1f\" Environment=\"dev\" SubEnvironment=\"none\" LambdaDeploymentPreference=\"AllAtOnce\" LoggingSubscriptionEndpointArn=\"arn:aws:logs:eu-west-2:885513274347:destination:csls_cw_logs_destination_prodpython-2\""
image_repositories = []
signing_profiles = "AccountInterventionsFunction=\"SigningProfile_bdzyxbYzrSD8\" AuthTokenFunction=\"SigningProfile_bdzyxbYzrSD8\" AuthUserInfoFunction=\"SigningProfile_bdzyxbYzrSD8\" LoginFunction=\"SigningProfile_bdzyxbYzrSD8\" MfaFunction=\"SigningProfile_bdzyxbYzrSD8\" OrchAuthCodeFunction=\"SigningProfile_bdzyxbYzrSD8\" SecretString-JAVA_LAYER}}-cd3ae82ef4=\"SigningProfile_bdzyxbYzrSD8\" StartFunction=\"SigningProfile_bdzyxbYzrSD8\" TicfCriFunction=\"SigningProfile_bdzyxbYzrSD8\" UserExistsFunction=\"SigningProfile_bdzyxbYzrSD8\""

[authdev1.deploy.parameters]
stack_name = "authdev1-api"
resolve_s3 = false
s3_bucket = "authdev1-api-pipeline-githubartifactsourcebucket-nzhdk5isnl7b"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "VpcStackName=\"vpc\" CodeSigningConfigArn=\"arn:aws:lambda:eu-west-2:975050272416:code-signing-config:csc-02724be8887ae9448\" PermissionsBoundary=\"arn:aws:iam::975050272416:policy/authdev1-api-pipeline-AppProgrammaticPermissionsBoundary-06077d801cdf\" Environment=\"dev\" SubEnvironment=\"authdev1\" LambdaDeploymentPreference=\"AllAtOnce\" LoggingSubscriptionEndpointArn=\"arn:aws:logs:eu-west-2:885513274347:destination:csls_cw_logs_destination_prodpython-2\""
image_repositories = []
signing_profiles = "AccountInterventionsFunction=\"SigningProfile_bdzyxbYzrSD8\" AuthTokenFunction=\"SigningProfile_bdzyxbYzrSD8\" AuthUserInfoFunction=\"SigningProfile_bdzyxbYzrSD8\" LoginFunction=\"SigningProfile_bdzyxbYzrSD8\" MfaFunction=\"SigningProfile_bdzyxbYzrSD8\" OrchAuthCodeFunction=\"SigningProfile_bdzyxbYzrSD8\" SecretString-JAVA_LAYER}}-cd3ae82ef4=\"SigningProfile_bdzyxbYzrSD8\" StartFunction=\"SigningProfile_bdzyxbYzrSD8\" TicfCriFunction=\"SigningProfile_bdzyxbYzrSD8\" UserExistsFunction=\"SigningProfile_bdzyxbYzrSD8\""

[authdev2.deploy.parameters]
stack_name = "authdev2-api"
resolve_s3 = false
s3_bucket = "authdev2-api-pipeline-githubartifactsourcebucket-ppkafuj1qi9o"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "VpcStackName=\"vpc\" CodeSigningConfigArn=\"arn:aws:lambda:eu-west-2:975050272416:code-signing-config:csc-0725ac7ac42622250\" PermissionsBoundary=\"arn:aws:iam::975050272416:policy/authdev2-api-pipeline-AppProgrammaticPermissionsBoundary-06d4fe8cd0ad\" Environment=\"dev\" SubEnvironment=\"authdev2\" LambdaDeploymentPreference=\"AllAtOnce\" LoggingSubscriptionEndpointArn=\"arn:aws:logs:eu-west-2:885513274347:destination:csls_cw_logs_destination_prodpython-2\""
image_repositories = []
signing_profiles = "AccountInterventionsFunction=\"SigningProfile_bdzyxbYzrSD8\" AuthTokenFunction=\"SigningProfile_bdzyxbYzrSD8\" AuthUserInfoFunction=\"SigningProfile_bdzyxbYzrSD8\" LoginFunction=\"SigningProfile_bdzyxbYzrSD8\" MfaFunction=\"SigningProfile_bdzyxbYzrSD8\" OrchAuthCodeFunction=\"SigningProfile_bdzyxbYzrSD8\" SecretString-JAVA_LAYER}}-cd3ae82ef4=\"SigningProfile_bdzyxbYzrSD8\" StartFunction=\"SigningProfile_bdzyxbYzrSD8\" TicfCriFunction=\"SigningProfile_bdzyxbYzrSD8\" UserExistsFunction=\"SigningProfile_bdzyxbYzrSD8\""
