AWSTemplateFormatVersion: "2010-09-09"
Resources:
  FubarFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub
        - ${Env}-fubar-lambda
        - Env: !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment]
      AutoPublishAlias: active
      CodeUri: ./frontend-api/build/distributions/frontend-api.zip
      Handler: uk.gov.di.authentication.frontendapi.lambda.ResetPasswordHandler::handleRequest
      Environment:
        Variables:
          DEFAULT_OTP_CODE_EXPIRY: !Sub
            - "{{resolve:ssm:/deploy/${env}/otp_code_ttl_duration}}"
            - env:
                !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment]
          DYNAMO_ARN_PREFIX: !Sub
            - "arn:aws:dynamodb:${AWS::Region}:${DataStoreAccountId}:table/"
            - DataStoreAccountId:
                !FindInMap [
                  EnvironmentConfiguration,
                  !Ref Environment,
                  dataStoreAccountId,
                ]
          EMAIL_OTP_ACCOUNT_CREATION_CODE_EXPIRY: !Sub
            - "{{resolve:ssm:/deploy/${env}/email_acct_creation_otp_code_ttl_duration}}"
            - env:
                !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment]
          EMAIL_QUEUE_URL: !GetAtt EmailNotificationQueue.QueueUrl
          INTERNAl_SECTOR_URI: !If
            - IsNotProduction
            - !If
              - UseSubEnvironment
              - !Sub "https://identity.${SubEnvironment}.${Environment}.account.gov.uk"
              - !Sub "https://identity.${Environment}.account.gov.uk"
            - "https://identity.account.gov.uk"
          REDIS_KEY: "session"
          TERMS_CONDITIONS_VERSION: !Sub
            - "{{resolve:ssm:/deploy/${env}/terms_conditions_version}}"
            - env:
                !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment]
          TXMA_AUDIT_QUEUE_URL: !GetAtt AuthInternalApiTxMAAuditQueue.QueueUrl
          USE_STRONGLY_CONSISTENT_READS: !Sub
            - "{{resolve:ssm:/deploy/${env}/use_strongly_consistent_reads}}"
            - env:
                !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment]
      LoggingConfig:
        LogGroup: !Ref FubarFunctionLogGroup
      Policies:
        - !Ref LambdaBasicExecutionPolicy
        - !Ref AuditEventsSnsPolicy
        - !Ref AuditSigningKeyLambdaKmsSigningPolicy
        - !Ref AuthInternalApiTxMAAuditQueueAccessPolicy
        - !Ref DynamoAccountModifiersReadWritePolicy
        - !Ref DynamoAuthSessionStoreReadWriteAccessPolicy
        - !Ref DynamoClientRegistryReadAccessPolicy
        - !Ref DynamoCommonPasswordsReadAccessPolicy
        - !Ref DynamoUserReadWriteAccessPolicy
        - !Ref RedisParametersAccessPolicy
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - Fn::ImportValue: !Sub ${VpcStackName}-PrivateSubnetIdA
          - Fn::ImportValue: !Sub ${VpcStackName}-PrivateSubnetIdB
          - Fn::ImportValue: !Sub ${VpcStackName}-PrivateSubnetIdC

  FubarFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt FubarFunction.Arn
      Principal: apigateway.amazonaws.com

  FubarFunctionAliasPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref FubarFunction.Alias
      Principal: apigateway.amazonaws.com

  FubarFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub
        - /aws/lambda/${Env}-fubar-lambda
        - Env: !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment]
      KmsKeyId: !GetAtt MainKmsKey.Arn
      RetentionInDays:
        !FindInMap [
          EnvironmentConfiguration,
          !Ref Environment,
          cloudwatchLogRetentionInDays,
        ]
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-FubarFunctionLogGroup"
        - Key: Environment
          Value: !Ref Environment
        - Key: Source
          Value: govuk-one-login/authentication-api/ci/cloudformation/auth/function/fubar.yaml
