AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MfaFunction:
    Type: AWS::Serverless::Function # This function uses redis
    Properties:
      FunctionName: !Sub
        - ${Env}-mfa-lambda
        - Env: !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment]
      AutoPublishAlias: active
      CodeUri: ./frontend-api/build/distributions/frontend-api.zip
      Handler: uk.gov.di.authentication.frontendapi.lambda.MfaHandler::handleRequest
      Environment:
        Variables:
          DEFAULT_OTP_CODE_EXPIRY:
            !FindInMap [
              EnvironmentConfiguration,
              !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment],
              otpCodeTtlDuration,
            ]
          DYNAMO_ARN_PREFIX: !Sub
            - "arn:aws:dynamodb:${AWS::Region}:${DataStoreAccountId}:table/"
            - DataStoreAccountId:
                !FindInMap [
                  EnvironmentConfiguration,
                  !Ref Environment,
                  dataStoreAccountId,
                ]
          EMAIL_OTP_ACCOUNT_CREATION_CODE_EXPIRY:
            !FindInMap [
              EnvironmentConfiguration,
              !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment],
              emailAcctCreationOtpCodeTtlDuration,
            ]
          EMAIL_QUEUE_URL: !GetAtt EmailNotificationQueue.QueueUrl
          INTERNAl_SECTOR_URI: !If
            - IsNotProduction
            - !If
              - UseSubEnvironment
              - !Sub "https://identity.${SubEnvironment}.${Environment}.account.gov.uk"
              - !Sub "https://identity.${Environment}.account.gov.uk"
            - "https://identity.account.gov.uk"
          LOCKOUT_COUNT_TTL:
            !FindInMap [
              EnvironmentConfiguration,
              !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment],
              lockoutCountTtl,
            ]
          LOCKOUT_DURATION:
            !FindInMap [
              EnvironmentConfiguration,
              !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment],
              lockoutDuration,
            ]
          REDIS_KEY: "session"
          SUPPORT_REAUTH_SIGNOUT_ENABLED:
            !FindInMap [
              EnvironmentConfiguration,
              !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment],
              supportReauthSignoutEnabled,
            ]
          TEST_CLIENTS_ENABLED:
            !FindInMap [
              EnvironmentConfiguration,
              !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment],
              testClientsEnabled,
            ]
          TXMA_AUDIT_QUEUE_URL: !GetAtt AuthInternalApiTxMAAuditQueue.QueueUrl
          USE_STRONGLY_CONSISTENT_READS:
            !FindInMap [
              EnvironmentConfiguration,
              !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment],
              useStronglyConsistentReads,
            ]
      LoggingConfig:
        LogGroup: !Ref MfaFunctionLogGroup
      Policies:
        - !Ref LambdaBasicExecutionPolicy
        - !Ref AuditEventsSnsPolicy
        - !Ref AuditSigningKeyLambdaKmsSigningPolicy
        - !Ref AuthInternalApiTxMAAuditQueueAccessPolicy
        - !Ref DynamoAuthSessionStoreReadWriteAccessPolicy
        - !Ref DynamoClientRegistryReadAccessPolicy
        - !Ref RedisParametersAccessPolicy
        - !Ref DynamoUserReadWriteAccessPolicy
        - !If [
            ProvisionTestClientSecret,
            !Ref TestClientEmailAllowListSecretAccessPolicy,
            !Ref AWS::NoValue,
          ]
      ProvisionedConcurrencyConfig: !If
        - EnableProvisionedConcurrency
        - ProvisionedConcurrentExecutions:
            !FindInMap [
              EnvironmentConfiguration,
              !Ref Environment,
              lambdaMinConcurrency,
              DefaultValue: 0,
            ]
        - !Ref AWS::NoValue
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - Fn::ImportValue: !Sub ${VpcStackName}-PrivateSubnetIdA
          - Fn::ImportValue: !Sub ${VpcStackName}-PrivateSubnetIdB
          - Fn::ImportValue: !Sub ${VpcStackName}-PrivateSubnetIdC

  MfaFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt MfaFunction.Arn
      Principal: apigateway.amazonaws.com

  MfaFunctionAliasPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref MfaFunction.Alias
      Principal: apigateway.amazonaws.com

  MfaFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub
        - /aws/lambda/${Env}-mfa-lambda
        - Env: !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment]
      KmsKeyId: !GetAtt MainKmsKey.Arn
      RetentionInDays:
        !FindInMap [
          EnvironmentConfiguration,
          !Ref Environment,
          cloudwatchLogRetentionInDays,
        ]
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-MfaFunctionLogGroup"
        - Key: Environment
          Value: !Ref Environment
        - Key: Source
          Value: govuk-one-login/authentication-api/ci/cloudformation/auth/function/mfa.yaml

  MfaFunctionErrorMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      FilterName: !Sub
        - ${Env}-mfa-errors
        - Env: !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment]
      FilterPattern: '{($.level = "ERROR")}'
      LogGroupName: !Ref MfaFunctionLogGroup
      MetricTransformations:
        - MetricName: !Sub
            - ${Env}-mfa-error-count
            - Env:
                !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment]
          MetricNamespace: LambdaErrorsNamespace
          MetricValue: 1

  MfaFunctionErrorCloudwatchAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions: !If
        - UseAlarmActions
        - - !Sub "{{resolve:ssm:/deploy/${Environment}/slack_alert_notification_topic_arn}}"
        - []
      AlarmDescription: !Sub
        - "${AlarmThreshold} or more number of errors have occurred in the ${Env}-mfa-lambda function. ${RunbookLink}"
        - AlarmThreshold:
            !FindInMap [
              EnvironmentConfiguration,
              !Ref Environment,
              lambdaLogAlarmThreshold,
              DefaultValue: 5,
            ]
          Env: !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment]
          RunbookLink:
            !FindInMap [
              LambdaConfiguration,
              "mfa",
              RunbookLink,
              DefaultValue: "",
            ]
      AlarmName: !Sub
        - ${Env}-mfa-alarm
        - Env: !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment]
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      MetricName: !Sub
        - ${Env}-mfa-error-count
        - Env: !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment]
      Namespace: LambdaErrorsNamespace
      Period: 3600
      Statistic: Sum
      Threshold:
        !FindInMap [
          EnvironmentConfiguration,
          !Ref Environment,
          lambdaLogAlarmThreshold,
          DefaultValue: 5,
        ]

  MfaFunctionErrorRateCloudwatchAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions: !If
        - UseAlarmActions
        - - !Sub "{{resolve:ssm:/deploy/${Environment}/slack_alert_notification_topic_arn}}"
        - []
      AlarmDescription: !Sub
        - "Lambda error rate of ${ErrorRateThreshold}% has been reached in the ${Env}-mfa-lambda. ${RunbookLink}"
        - Env: !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment]
          ErrorRateThreshold:
            !FindInMap [
              EnvironmentConfiguration,
              !Ref Environment,
              lambdaLogAlarmErrorRateThreshold,
              DefaultValue: 10,
            ]
          RunbookLink:
            !FindInMap [
              LambdaConfiguration,
              "mfa",
              RunbookLink,
              DefaultValue: "",
            ]
      AlarmName: !Sub
        - ${Env}-mfa-error-rate-alarm
        - Env: !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment]
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      Metrics:
        - Id: e1
          Label: "Error Rate"
          ReturnData: true
          Expression: (m2/m1)*100
        - Id: m1
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: AWS/Lambda
              MetricName: Invocations
              Dimensions:
                - Name: FunctionName
                  Value: !Sub
                    - ${Env}-mfa-lambda
                    - Env:
                        !If [
                          UseSubEnvironment,
                          !Ref SubEnvironment,
                          !Ref Environment,
                        ]
            Period: 60
            Stat: Sum
            Unit: Count
        - Id: m2
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: AWS/Lambda
              MetricName: Errors
              Dimensions:
                - Name: FunctionName
                  Value: !Sub
                    - ${Env}-mfa-lambda
                    - Env:
                        !If [
                          UseSubEnvironment,
                          !Ref SubEnvironment,
                          !Ref Environment,
                        ]
            Period: 60
            Stat: Sum
            Unit: Count
      Threshold:
        !FindInMap [
          EnvironmentConfiguration,
          !Ref Environment,
          lambdaLogAlarmErrorRateThreshold,
          DefaultValue: 10,
        ]

  MfaFunctionSubscriptionFilter:
    Condition: IsSplunkEnabled
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      DestinationArn: !Ref LoggingSubscriptionEndpointArn
      FilterPattern: ""
      LogGroupName: !Ref MfaFunctionLogGroup

  MfaFunctionScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Condition: NotSubEnvironment
    # Need to depend on the auto deployed version alias: "<function_logical_id> + Alias + <the_alias_name>"
    DependsOn: MfaFunctionAliasactive
    Properties:
      MinCapacity:
        !FindInMap [
          EnvironmentConfiguration,
          !Ref Environment,
          lambdaMinConcurrency,
          DefaultValue: 0,
        ]
      MaxCapacity:
        !FindInMap [
          EnvironmentConfiguration,
          !Ref Environment,
          lambdaMaxConcurrency,
          DefaultValue: 5,
        ]
      RoleARN: !Sub "arn:aws:iam::${AWS::AccountId}:role/aws-service-role/lambda.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_LambdaConcurrency"
      ResourceId: !Join
        - ":"
        - - "function"
          - !Select [6, !Split [":", !GetAtt MfaFunction.Arn]]
          - "active"
      ScalableDimension: lambda:function:ProvisionedConcurrency
      ServiceNamespace: lambda

  MfaFunctionAutoScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Condition: NotSubEnvironment
    DependsOn: MfaFunctionScalableTarget
    Properties:
      PolicyName: !Sub
        - "LambdaProvisionedConcurrency:${Env}-mfa-lambda"
        - Env: !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment]
      PolicyType: TargetTrackingScaling
      ResourceId: !Join
        - ":"
        - - "function"
          - !Select [6, !Split [":", !GetAtt MfaFunction.Arn]]
          - "active"
      ScalableDimension: lambda:function:ProvisionedConcurrency
      ServiceNamespace: lambda
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: LambdaProvisionedConcurrencyUtilization
        TargetValue:
          !FindInMap [
            EnvironmentConfiguration,
            !Ref Environment,
            lambdaAutoscalingTargetValue,
            DefaultValue: "0.6",
          ]
