#!/usr/bin/env bash

STATE_OUT="authdev2-shared-terraform.tfstate"
STATE_IN="frontend-authdev2-terraform.tfstate"

function migrate() {
  terraform state mv -state "${STATE_IN}" -state-out "${STATE_OUT}" "$1" "$2"
}

migrate aws_elasticache_subnet_group.frontend_redis_session_store aws_elasticache_subnet_group.frontend_redis_session_store
migrate aws_elasticache_replication_group.frontend_sessions_store aws_elasticache_replication_group.frontend_sessions_store
# security group and rules
migrate aws_security_group.frontend_redis_security_group aws_security_group.frontend_redis_security_group
migrate aws_security_group_rule.allow_incoming_frontend_redis_from_private_subnet aws_security_group_rule.allow_incoming_frontend_redis_from_private_subnet
migrate aws_security_group_rule.allow_incoming_frontend_redis_from_new_auth aws_security_group_rule.allow_incoming_frontend_redis_from_new_auth
migrate aws_security_group.allow_access_to_frontend_redis aws_security_group.allow_access_to_frontend_redis
migrate aws_security_group_rule.allow_connection_to_frontend_redis aws_security_group_rule.allow_connection_to_frontend_redis
