name: Deploy Orchestration

env:
  AWS_REGION: eu-west-2

on:
  workflow_call:
    secrets:
      ORCH_GH_ACTIONS_ROLE_ARN:
        required: true
      ORCH_ARTIFACT_BUCKET_NAME:
        required: true
      ORCH_SIGNING_PROFILE_NAME:
        required: true
    inputs:
      run_unit_tests:
        description: "Boolean to run unit tests before deploying"
        type: boolean
        default: false

jobs:
  build:
    if: ${{ inputs.run_unit_tests == true }}
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Check out repository code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up JDK 17
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 #v5.2.0
        with:
          java-version: "17"
          distribution: "corretto"
          cache: gradle
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v4
        with:
          gradle-version: wrapper
          cache-read-only: false
      - name: Build Cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            .gradle/
            */build/
            !*/build/reports
            !*/build/jacoco
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-${{ github.event.pull_request.base.sha }}
            ${{ runner.os }}-build-
      - name: Run Build
        run: ./gradlew --parallel build -x test -x spotlessApply -x spotlessCheck

  run-unit-tests:
    if: ${{ inputs.run_unit_tests == true }}
    runs-on: ubuntu-24.04-arm
    needs:
      - build
    steps:
      - name: Check out repository code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Set up JDK 17
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 #v5.2.0
        with:
          java-version: "17"
          distribution: "corretto"
          cache: gradle
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v4
        with:
          gradle-version: wrapper
          cache-read-only: true
      - name: Restore Build Cache
        uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            .gradle/
            */build/
            !*/build/reports
            !*/build/jacoco
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-${{ github.event.pull_request.base.sha }}
            ${{ runner.os }}-build-
      - name: Run Unit Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew client-registry-api:test doc-checking-app-api:test ipv-api:test oidc-api:test orchestration-shared:test jacocoTestReport sis-api:test

  run-alerting-tests:
    if: ${{ inputs.run_unit_tests == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install dependencies
        run: npm ci --ignore-scripts
        working-directory: ./orchestration-alerting
      - name: Run Unit Tests
        run: npm test
        working-directory: ./orchestration-alerting

  deploy:
    runs-on: ubuntu-latest
    needs:
      - run-unit-tests
      - run-alerting-tests
    if: |
      always() &&
      (needs.run-unit-tests.result == 'success' || needs.run-unit-tests.result == 'skipped') &&
      (needs.run-alerting-tests.result == 'success' || needs.run-alerting-tests.result == 'skipped')
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up SAM cli
        uses: aws-actions/setup-sam@89ddb14d60e682855e3fea4be85b3c56485de310 # v2
        with:
          use-installer: true
          version: 1.159.1

      - name: Set up AWS creds
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # v6.2.0
        with:
          role-to-assume: ${{ secrets.ORCH_GH_ACTIONS_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Set up JDK 17
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 #v5.2.0
        with:
          java-version: "17"
          distribution: "corretto"
          cache: gradle

      - name: SAM build
        run: |
          ./gradlew --no-daemon --parallel :oidc:buildZip :ipv-api:buildZip :doc-checking-app-api:buildZip :client-registry-api:buildZip :sis-api:buildZip
          sam build --parallel

      - name: Deploy SAM app
        uses: govuk-one-login/devplatform-upload-action@64e46134b4108ebfa1cf2a64fee00782f8e2e8cf # v3.8
        with:
          artifact-bucket-name: ${{ secrets.ORCH_ARTIFACT_BUCKET_NAME }}
          signing-profile-name: ${{ secrets.ORCH_SIGNING_PROFILE_NAME }}
          working-directory: .aws-sam/build
