name: Deploy Account Management Dev

env:
  AWS_REGION: eu-west-2

#gha role is build Auth github actions role in Gds dev Account
#Artifact bucket is Build Auth deploy github artifcat Source bucket
#Destination Bucket is auth-lambda-signed bucket from prod tooling account

on: 
  workflow_run:
    workflows: ["Build modules"]
    types:
      - completed

jobs:
  deploy:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up AWS credentials for Dev
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::653994557586:role/dev-auth-deploy-pipeline-GitHubActionsRole-QrtGginNnjDD
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Download and copy Account Management signed lambda zip
        working-directory: ci/terraform/account-management
        run: |
          aws s3 cp s3://${{ secrets.DESTINATION_BUCKET }} ./artifacts \
            --recursive --exclude "*" \
            --include "signed-account-management-api-${{ github.sha }}-*"
          mv artifacts/signed-account-management-*.zip artifacts/account-management-api.zip

      - name: Upload Account Management Terraform files to Dev
        working-directory: ci/terraform
        run: |
          zip -r account-management.zip .
          S3_RESPONSE=`aws s3api put-object \
            --bucket dev-auth-deploy-pipeline-githubartifactsourcebuck-ssdefc91xjh6 \
            --key account-management.zip \
            --body account-management.zip \
            --metadata "repository=$GITHUB_REPOSITORY,commitsha=$GITHUB_SHA,committag=$GIT_TAG,commitmessage=$COMMIT_MSG"`
          VERSION=`echo $S3_RESPONSE | jq .VersionId -r`
          echo "VERSION=$VERSION" >> $GITHUB_ENV
