name: TEST Deploy Orchestration dev
run-name: TEST Deploy Orch to ${{ inputs.environment }}

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to run against"
        type: choice
        required: true
        options:
          - orchdev1

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up SAM cli
        uses: aws-actions/setup-sam@89ddb14d60e682855e3fea4be85b3c56485de310 # v2
        with:
          use-installer: true
          version: 1.159.1

      - name: Set up AWS creds
        uses: aws-actions/configure-aws-credentials@517a711dbcd0e402f90c77e7e2f81e849156e31d # v6.2.2
        with:
          role-to-assume: ${{ secrets.ORCH_GH_ACTIONS_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Set up JDK 17
        uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a #v5.5.0
        with:
          java-version: "17"
          distribution: "corretto"
          cache: gradle

      - name: SAM build
        run: |
          ./gradlew --no-daemon --parallel :oidc:buildZip :ipv-api:buildZip :doc-checking-app-api:buildZip :client-registry-api:buildZip :sis-api:buildZip
          sam build --parallel

      - name: Deploy SAM app
        uses: govuk-one-login/devplatform-upload-action@64e46134b4108ebfa1cf2a64fee00782f8e2e8cf # v3.8
        with:
          artifact-bucket-name: ${{ secrets.ORCH_ARTIFACT_BUCKET_NAME }}
          signing-profile-name: ${{ secrets.ORCH_SIGNING_PROFILE_NAME }}
          working-directory: .aws-sam/build
