name: "SP - Build and deploy Auth ext and Internal API"

on:
  push:
    branches:
      - main
    paths-ignore:
      - "ci/cloudformation/account-management/**"
      - "ci/cloudformation/account-data/**"
      - "ci/cloudformation/stubs/**"
      - "ci/cloudformation/utils/**"
      - "template.yaml"
      - "docs/**"
      - "**/README.md"
      - "integration-tests/**"
      - "delivery-receipts-integration-tests/**"
      - "local-running/**"
      - "notifications/**"
      - "quality-gate.manifest.json"
      - "account-management-api/**"
      - "account-management-integration-tests/**"
      - "account-data-api/**"
      - "account-data-api-integration-tests/**"
      - "test-services-api/**"
      - "utils/**"
      - "ticf-cri-stub/**"
      - "interventions-api-stub/**"
      - "oidc-api/**"
      - "orchestration-*/**"
      - "doc-checking-app-api/**"
      - "client-registry-api/**"
      - "oidc-api-integration-tests/**"
      - "ipv-api-integration-tests/**"
      - "identity-shared/**"
      - "http/**"
      - "tools/**"

env:
  AWS_REGION: eu-west-2
  JAVA_VERSION: 17
  JAVA_DISTRIBUTION: corretto
  RAIN_VERSION: v1.23.0
  RAIN_ARCH: linux-amd64

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up SAM cli
        uses: aws-actions/setup-sam@89ddb14d60e682855e3fea4be85b3c56485de310 # v2
        with:
          use-installer: true
          version: 1.159.1

      - name: Set up AWS creds
        uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
        with:
          role-to-assume: ${{ secrets.GH_ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up JDK 17
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 #v5.7.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: gradle

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v4
        with:
          gradle-version: wrapper
          cache-read-only: false

      - name: Gradle build
        run: |
          ./gradlew --no-daemon --parallel :auth-external-api:buildZip :frontend-api:buildZip :ipv-api:buildZip :delivery-receipts-api:buildZip :sis-api:buildZip

      - name: Install Rain
        uses: ./.github/actions/install-rain
        with:
          version: ${{ env.RAIN_VERSION }}
          arch: ${{ env.RAIN_ARCH }}
          sha256: "2fdfe059566acf15ad23e014a7856e88f6af61710854208a93526eec80f4078f"

      - name: Generate auth template
        run: "./scripts/merge-templates.sh"
        env:
          TEMPLATE_SOURCE_DIR: ci/cloudformation/auth
          TEMPLATE_FILE: auth-template.yaml

      - name: SAM build
        run: |
          sam validate --lint -t auth-template.yaml
          sam build --parallel -t auth-template.yaml

      - name: Extract version info
        id: version_info
        uses: ./.github/actions/extract-version-info

      - name: Deploy SAM app
        uses: govuk-one-login/devplatform-upload-action@ec09f4b1f8648fe21dd18a40a2d8e2fa94d0ad41 # v4.2.0
        with:
          artifact-bucket-name: ${{ secrets.ARTIFACT_SOURCE_BUCKET_NAME }}
          signing-profile-name: ${{ secrets.SIGNING_PROFILE_NAME }}
          working-directory: .aws-sam/build
          version: ${{ steps.version_info.outputs.version }}
