name: "(TW) DEV: Build and deploy API modules"
env:
  AWS_REGION: eu-west-2
  DEPLOYER_ROLE: arn:aws:iam::706615647326:role/deployers/dev-github-actions-publish-to-s3-for-code-signing
  SOURCE_BUCKET: di-auth-lambda-source-20220215165054622300000001
  SIGNING_PROFILE: di_auth_lambda_signing_20220214175605677200000001
  DESTINATION_BUCKET: di-auth-lambda-signed-20220215165009815000000001
  GHA_ROLE: arn:aws:iam::653994557586:role/dev-auth-deploy-pipeline-GitHubActionsRole-QrtGginNnjDD
  ARTIFACT_BUCKET: dev-auth-deploy-pipeline-githubartifactsourcebuck-ssdefc91xjh6
  ARTIFACT_LOOKUP_TABLE: arn:aws:dynamodb:eu-west-2:706615647326:table/di-auth-non-production-artifact-lookup

on:
  workflow_dispatch:
  # TODO: Remove this push trigger once tested
  push:
    branches:
      - AUT-2802/stop-repeat-deploy-same-lambda

concurrency:
  group: "build-and-deploy-api-modules-dev"
  cancel-in-progress: false

jobs:
  pr-data:
    name: Get job metadata
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      # These are not relevant for dev triggers, but are included to ensure all S3 metadata is populated
      pr_number: "-1"
      pr_title: "dev trigger"
      pr_merged_at: "-1"
      pr_merge_commit_sha: ${{ github.sha }}
      pr_api_url: "-1"
      pr_html_url: "-1"

      commit_api_url: ${{ steps.data.outputs.commit_api_url }}

      repo_full_name: ${{ steps.data.outputs.repo_full_name }}
      repo_owner: ${{ steps.data.outputs.repo_owner }}
      repo_name: ${{ steps.data.outputs.repo_name }}

      repository: ${{ steps.data.outputs.repo_full_name }}
      commitsha: ${{ github.sha }}
      commitmessage: "dev trigger"

    steps:
      - name: Get commit data
        uses: actions/github-script@v7
        id: get_commit_data
        with:
          script: |
            return await github.rest.repos.getCommit({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: context.sha
              });
      - name: Output data
        id: data
        run: |
          echo "Exporting commit data to \$GITHUB_OUTPUT"
          {
            echo 'commit_api_url=${{ fromJson(steps.get_commit_data.outputs.result).url }}'
          } >> "$GITHUB_OUTPUT"

          echo "Exporting repo data to \$GITHUB_OUTPUT"
          {
            echo 'repo_full_name=${{ github.repository }}'
            echo 'repo_owner=${{ github.repository_owner }}'
            echo 'repo_name=${{ github.event.repository.name }}'
          } >> "$GITHUB_OUTPUT"

  set-up:
    name: Set up environment
    runs-on: ubuntu-latest
    outputs:
      aws_region: ${{ env.AWS_REGION }}
      deployer_role: ${{ steps.secrets.outputs.DEPLOYER_ROLE }}
      promotion_role: ${{ steps.secrets.outputs.PROMOTION_ROLE }}
      source_bucket: ${{ steps.secrets.outputs.SOURCE_BUCKET }}
      signing_profile: ${{ steps.secrets.outputs.SIGNING_PROFILE }}
      destination_bucket: ${{ steps.secrets.outputs.DESTINATION_BUCKET }}
      artifact_bucket: ${{ steps.secrets.outputs.ARTIFACT_BUCKET }}
      artifact_lookup_table: ${{ steps.secrets.outputs.ARTIFACT_LOOKUP_TABLE  }}
    steps:
      - id: secrets
        run: |
          {
            echo "DEPLOYER_ROLE=${{ env.DEPLOYER_ROLE }}"
            echo "SOURCE_BUCKET=${{ env.SOURCE_BUCKET }}"
            echo "SIGNING_PROFILE=${{ env.SIGNING_PROFILE }}"
            echo "DESTINATION_BUCKET=${{ env.DESTINATION_BUCKET }}"
            echo "PROMOTION_ROLE=${{ env.GHA_ROLE }}"
            echo "ARTIFACT_BUCKET=${{ env.ARTIFACT_BUCKET }}"
            echo "ARTIFACT_LOOKUP_TABLE=${{ env.ARTIFACT_LOOKUP_TABLE }}"
          } >> "$GITHUB_OUTPUT"

  build:
    name: Build modules
    needs: set-up
    strategy:
      matrix:
        module:
          - account-management-api
          - auth-external-api
          - client-registry-api
          - delivery-receipts-api
          - doc-checking-app-api
          - frontend-api
          - interventions-api-stub
          - ipv-api
          - oidc-api
          - test-services-api
          - ticf-cri-stub
          - utils
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/call_build-single-api-module.yml
    with:
      module_name: ${{ matrix.module }}
      aws_region: ${{ needs.set-up.outputs.aws_region }}
      aws_role: ${{ needs.set-up.outputs.deployer_role }}
      source_bucket: ${{ needs.set-up.outputs.source_bucket }}
      destination_bucket: ${{ needs.set-up.outputs.destination_bucket }}
      signing_profile: ${{ needs.set-up.outputs.signing_profile }}
      lookup_table: ${{ needs.set-up.outputs.artifact_lookup_table }}

  create-promotion-artifact-shared:
    name: Create Shared Promotion Artifact
    needs: set-up
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/call_create-shared-promotion-artifact.yml

  create-promotion-artifacts-simple-modules:
    name: Create Promotion Artifact
    needs:
      - set-up
      - build
    strategy:
      matrix:
        include:
          - module_name: account-management-api
            terraform_directory_name: account-management
          - module_name: auth-external-api
            terraform_directory_name: auth-external-api
          - module_name: delivery-receipts-api
            terraform_directory_name: delivery-receipts
          - module_name: interventions-api-stub
            terraform_directory_name: interventions-api-stub
          - module_name: test-services-api
            terraform_directory_name: test-services
          - module_name: ticf-cri-stub
            terraform_directory_name: ticf-cri-stub
          - module_name: utils
            terraform_directory_name: utils
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/call_create-simple-module-promotion-artifact.yml
    with:
      module_name: ${{ matrix.module_name }}
      terraform_directory_name: ${{ matrix.terraform_directory_name }}

  create-promotion-artifact-oidc:
    name: Create OIDC Promotion artifact
    needs:
      - set-up
      - build
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/call_create-oidc-promotion-artifact.yml
    with:
      oidc_api_module_name: oidc-api
      client_registry_api_module_name: client-registry-api
      doc_checking_app_api_module_name: doc-checking-app-api
      frontend_api_module_name: frontend-api
      ipv_api_module_name: ipv-api

      terraform_directory_name: oidc

  gather-and-trigger-codepipeline:
    name: Gather and trigger CodePipeline
    needs:
      - pr-data
      - set-up
      - create-promotion-artifact-shared
      - create-promotion-artifacts-simple-modules
      - create-promotion-artifact-oidc
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ needs.set-up.outputs.promotion_role }}
          aws-region: ${{ needs.set-up.outputs.aws_region }}

      - name: Download all promotion artifacts
        id: download_promotion_artifacts
        uses: actions/download-artifact@v4
        with:
          path: promotion-artifacts
          pattern: promotion_artifact_*
          merge-multiple: true

      - name: Upload single promotion artifact to S3
        working-directory: promotion-artifacts
        run: |
          echo "::group::Zip all promotion artifacts"
          zip -r authentication-api.zip .
          echo "::endgroup::"

          OBJECT_VERSION="$(aws s3api put-object \
            --bucket ${{ needs.set-up.outputs.artifact_bucket }} \
            --key authentication-api.zip \
            --body authentication-api.zip \
            --metadata '${{ toJson(needs.pr-data.outputs) }}' \
            --query VersionId --output text)"

          echo "Uploaded object version: $OBJECT_VERSION"
