name: "SP - Pre-merge checks for SAM API modules"

on:
  pull_request:
    paths:
      - "ci/cloudformation/auth/**"
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

env:
  AWS_REGION: eu-west-2
  RAIN_VERSION: v1.23.0
  RAIN_ARCH: linux-amd64

jobs:
  sam-validate:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up SAM cli
        uses: aws-actions/setup-sam@89ddb14d60e682855e3fea4be85b3c56485de310 # v2
        with:
          use-installer: true
          version: 1.165.0

      - name: Set up AWS creds
        uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
        with:
          role-to-assume: ${{ secrets.GH_ACTIONS_VALIDATE_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Rain
        uses: ./.github/actions/install-rain
        with:
          version: ${{ env.RAIN_VERSION }}
          arch: ${{ env.RAIN_ARCH }}
          sha256: "2fdfe059566acf15ad23e014a7856e88f6af61710854208a93526eec80f4078f"

      - name: Generate auth template
        run: "./scripts/merge-templates.sh"
        env:
          TEMPLATE_SOURCE_DIR: ci/cloudformation/auth
          TEMPLATE_FILE: auth-template.yaml

      - name: SAM Validate
        run: |
          sam validate --lint -t auth-template.yaml

      - name: Generate stubs template
        run: "./scripts/merge-templates.sh"
        env:
          TEMPLATE_SOURCE_DIR: ci/cloudformation/stubs
          TEMPLATE_FILE: stubs-template.yaml

      - name: SAM Validate
        run: |
          sam validate --lint -t stubs-template.yaml

      - name: Generate am template
        run: "./scripts/merge-templates.sh"
        env:
          TEMPLATE_SOURCE_DIR: ci/cloudformation/account-management
          TEMPLATE_FILE: am-template.yaml

      - name: SAM Validate
        run: |
          sam validate --lint -t am-template.yaml

      - name: Generate ad template
        run: "./scripts/merge-templates.sh"
        env:
          TEMPLATE_SOURCE_DIR: ci/cloudformation/account-data
          TEMPLATE_FILE: ad-template.yaml

      - name: SAM Validate
        run: |
          sam validate --lint -t ad-template.yaml
