name: Pre-merge checks for Python
on:
  pull_request:
    paths: ["**/*.py"]
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run black
        uses: psf/black@6fdf8a4af28071ed1d079c01122b34c5d587207a # 24.2.0
        with:
          version: "~=24.2"
