name: Warm configuration cache
env:
  JAVA_VERSION: "17"
  JAVA_DISTRIBUTION: "corretto"
  GRADLE_ENCRYPTION_KEY: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**/build.gradle"
      - "gradle.properties"
      - "gradle/libs.versions.toml"
      - "settings.gradle"
      - "gradle/wrapper/gradle-wrapper.properties"

jobs:
  style-checks:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 #v5.2.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
      - uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v4
        with:
          gradle-version: wrapper
          cache-read-only: false
      - name: Warm CC
        run: ./gradlew --no-daemon spotlessCheck
      - name: Save CC
        uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: .gradle/configuration-cache/
          key: ${{ runner.os }}-cc-style-checks-${{ hashFiles('**/build.gradle', 'gradle.properties', 'gradle/libs.versions.toml', 'settings.gradle') }}

  run-unit-tests:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 #v5.2.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
      - uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v4
        with:
          gradle-version: wrapper
          cache-read-only: false
      - name: Warm CC
        run: ./gradlew --parallel test jacocoTestReport -x integration-tests:test -x account-management-integration-tests:test -x delivery-receipts-integration-tests:test -x account-data-api-integration-tests:test -x spotlessApply -x spotlessCheck
      - name: Save CC
        uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: .gradle/configuration-cache/
          key: ${{ runner.os }}-cc-unit-tests-${{ hashFiles('**/build.gradle', 'gradle.properties', 'gradle/libs.versions.toml', 'settings.gradle') }}

  run-integration-tests-api:
    runs-on: ubuntu-24.04-arm
    services:
      localstack:
        image: localstack/localstack:4.6.0@sha256:5a97e0f9917a3f0d9630bb13b9d8ccf10cbe52f33252807d3b4e21418cc21348
        env:
          SERVICES: "sqs, sns, kms, ssm, s3, secretsmanager"
          DEFAULT_REGION: eu-west-2
          GATEWAY_LISTEN: 0.0.0.0:45678
          LOCALSTACK_HOST: localhost:45678
          TEST_AWS_ACCOUNT_ID: 123456789012
          KMS_PROVIDER: local-kms
        options: >-
          --add-host "notify.internal:host-gateway"
          --add-host "subscriber.internal:host-gateway"
        ports:
          - 45678:45678
      redis:
        image: redis:6.2.19-alpine@sha256:7fe72c486b910f6b1a9769c937dad5d63648ddee82e056f47417542dd40825bb
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
      dynamodb:
        image: amazon/dynamodb-local:3.0.0@sha256:2fed5e3a965a4ba5aa6ac82baec57058b5a3848e959d705518f3fd579a77e76b
        options: >-
          --health-cmd "curl http://localhost:8000"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 8000:8000
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 #v5.2.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
      - uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v4
        with:
          gradle-version: wrapper
          cache-read-only: false
      - name: Warm CC
        run: ./gradlew :integration-tests:test --tests "uk.gov.di.authentication.api.*" :integration-tests:jacocoTestReport -x spotlessApply -x spotlessCheck -x composeUp
      - name: Save CC
        uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: .gradle/configuration-cache/
          key: ${{ runner.os }}-cc-integration-api-${{ hashFiles('**/build.gradle', 'gradle.properties', 'gradle/libs.versions.toml', 'settings.gradle') }}

  run-integration-tests-services:
    runs-on: ubuntu-24.04-arm
    services:
      localstack:
        image: localstack/localstack:4.6.0@sha256:5a97e0f9917a3f0d9630bb13b9d8ccf10cbe52f33252807d3b4e21418cc21348
        env:
          SERVICES: "sqs, sns, kms, ssm, s3, secretsmanager"
          DEFAULT_REGION: eu-west-2
          GATEWAY_LISTEN: 0.0.0.0:45678
          LOCALSTACK_HOST: localhost:45678
          TEST_AWS_ACCOUNT_ID: 123456789012
          KMS_PROVIDER: local-kms
        options: >-
          --add-host "notify.internal:host-gateway"
          --add-host "subscriber.internal:host-gateway"
        ports:
          - 45678:45678
      redis:
        image: redis:6.2.19-alpine@sha256:7fe72c486b910f6b1a9769c937dad5d63648ddee82e056f47417542dd40825bb
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
      dynamodb:
        image: amazon/dynamodb-local:3.0.0@sha256:2fed5e3a965a4ba5aa6ac82baec57058b5a3848e959d705518f3fd579a77e76b
        options: >-
          --health-cmd "curl http://localhost:8000"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 8000:8000
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 #v5.2.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
      - uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v4
        with:
          gradle-version: wrapper
          cache-read-only: false
      - name: Warm CC
        run: ./gradlew :integration-tests:test --tests "uk.gov.di.authentication.services.*" --tests "uk.gov.di.authentication.shared.services.*" :integration-tests:jacocoTestReport -x spotlessApply -x spotlessCheck -x composeUp
      - name: Save CC
        uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: .gradle/configuration-cache/
          key: ${{ runner.os }}-cc-integration-services-${{ hashFiles('**/build.gradle', 'gradle.properties', 'gradle/libs.versions.toml', 'settings.gradle') }}

  run-integration-tests-orchestration:
    runs-on: ubuntu-24.04-arm
    services:
      localstack:
        image: localstack/localstack:4.6.0@sha256:5a97e0f9917a3f0d9630bb13b9d8ccf10cbe52f33252807d3b4e21418cc21348
        env:
          SERVICES: "sqs, sns, kms, ssm, s3, secretsmanager"
          DEFAULT_REGION: eu-west-2
          GATEWAY_LISTEN: 0.0.0.0:45678
          LOCALSTACK_HOST: localhost:45678
          TEST_AWS_ACCOUNT_ID: 123456789012
          KMS_PROVIDER: local-kms
        options: >-
          --add-host "notify.internal:host-gateway"
          --add-host "subscriber.internal:host-gateway"
        ports:
          - 45678:45678
      redis:
        image: redis:6.2.19-alpine@sha256:7fe72c486b910f6b1a9769c937dad5d63648ddee82e056f47417542dd40825bb
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
      dynamodb:
        image: amazon/dynamodb-local:3.0.0@sha256:2fed5e3a965a4ba5aa6ac82baec57058b5a3848e959d705518f3fd579a77e76b
        options: >-
          --health-cmd "curl http://localhost:8000"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 8000:8000
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 #v5.2.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
      - uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v4
        with:
          gradle-version: wrapper
          cache-read-only: false
      - name: Warm CC
        run: ./gradlew :integration-tests:test --tests "uk.gov.di.orchestration.*" :integration-tests:jacocoTestReport -x spotlessApply -x spotlessCheck -x composeUp
      - name: Save CC
        uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: .gradle/configuration-cache/
          key: ${{ runner.os }}-cc-integration-orchestration-${{ hashFiles('**/build.gradle', 'gradle.properties', 'gradle/libs.versions.toml', 'settings.gradle') }}

  run-integration-tests-utils:
    runs-on: ubuntu-24.04-arm
    services:
      localstack:
        image: localstack/localstack:4.6.0@sha256:5a97e0f9917a3f0d9630bb13b9d8ccf10cbe52f33252807d3b4e21418cc21348
        env:
          SERVICES: "sqs, sns, kms, ssm, s3, secretsmanager"
          DEFAULT_REGION: eu-west-2
          GATEWAY_LISTEN: 0.0.0.0:45678
          LOCALSTACK_HOST: localhost:45678
          TEST_AWS_ACCOUNT_ID: 123456789012
          KMS_PROVIDER: local-kms
        options: >-
          --add-host "notify.internal:host-gateway"
          --add-host "subscriber.internal:host-gateway"
        ports:
          - 45678:45678
      redis:
        image: redis:6.2.19-alpine@sha256:7fe72c486b910f6b1a9769c937dad5d63648ddee82e056f47417542dd40825bb
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
      dynamodb:
        image: amazon/dynamodb-local:3.0.0@sha256:2fed5e3a965a4ba5aa6ac82baec57058b5a3848e959d705518f3fd579a77e76b
        options: >-
          --health-cmd "curl http://localhost:8000"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 8000:8000
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 #v5.2.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
      - uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v4
        with:
          gradle-version: wrapper
          cache-read-only: false
      - name: Warm CC
        run: ./gradlew :integration-tests:test --tests "uk.gov.di.authentication.utils.*" --tests "uk.gov.di.authentication.queuehandlers.*" --tests "uk.gov.di.authentication.contract.*" :integration-tests:jacocoTestReport -x spotlessApply -x spotlessCheck -x composeUp
      - name: Save CC
        uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: .gradle/configuration-cache/
          key: ${{ runner.os }}-cc-integration-utils-${{ hashFiles('**/build.gradle', 'gradle.properties', 'gradle/libs.versions.toml', 'settings.gradle') }}

  run-account-management-and-delivery-receipts-tests:
    runs-on: ubuntu-24.04-arm
    services:
      localstack:
        image: localstack/localstack:4.6.0@sha256:5a97e0f9917a3f0d9630bb13b9d8ccf10cbe52f33252807d3b4e21418cc21348
        env:
          SERVICES: "sqs, sns, kms, ssm, s3, secretsmanager"
          DEFAULT_REGION: eu-west-2
          GATEWAY_LISTEN: 0.0.0.0:45678
          LOCALSTACK_HOST: localhost:45678
          TEST_AWS_ACCOUNT_ID: 123456789012
          KMS_PROVIDER: local-kms
        options: >-
          --add-host "notify.internal:host-gateway"
          --add-host "subscriber.internal:host-gateway"
        ports:
          - 45678:45678
      redis:
        image: redis:6.2.19-alpine@sha256:7fe72c486b910f6b1a9769c937dad5d63648ddee82e056f47417542dd40825bb
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
      dynamodb:
        image: amazon/dynamodb-local:3.0.0@sha256:2fed5e3a965a4ba5aa6ac82baec57058b5a3848e959d705518f3fd579a77e76b
        options: >-
          --health-cmd "curl http://localhost:8000"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 8000:8000
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 #v5.2.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
      - uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v4
        with:
          gradle-version: wrapper
          cache-read-only: false
      - name: Warm CC
        run: |
          ./gradlew :account-management-integration-tests:test :account-management-integration-tests:jacocoTestReport -x spotlessApply -x spotlessCheck -x composeUp
          ./gradlew :delivery-receipts-integration-tests:test :delivery-receipts-integration-tests:jacocoTestReport -x spotlessApply -x spotlessCheck -x composeUp
      - name: Save CC
        uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: .gradle/configuration-cache/
          key: ${{ runner.os }}-cc-integration-account-mgmt-${{ hashFiles('**/build.gradle', 'gradle.properties', 'gradle/libs.versions.toml', 'settings.gradle') }}

  run-account-data-api-integration-tests:
    runs-on: ubuntu-24.04-arm
    services:
      localstack:
        image: localstack/localstack:4.6.0@sha256:5a97e0f9917a3f0d9630bb13b9d8ccf10cbe52f33252807d3b4e21418cc21348
        env:
          SERVICES: "sqs, sns, kms, ssm, s3, secretsmanager"
          DEFAULT_REGION: eu-west-2
          GATEWAY_LISTEN: 0.0.0.0:45678
          LOCALSTACK_HOST: localhost:45678
          TEST_AWS_ACCOUNT_ID: 123456789012
          KMS_PROVIDER: local-kms
        options: >-
          --add-host "notify.internal:host-gateway"
          --add-host "subscriber.internal:host-gateway"
        ports:
          - 45678:45678
      dynamodb:
        image: amazon/dynamodb-local:3.0.0@sha256:2fed5e3a965a4ba5aa6ac82baec57058b5a3848e959d705518f3fd579a77e76b
        options: >-
          --health-cmd "curl http://localhost:8000"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 8000:8000
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 #v5.2.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
      - uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v4
        with:
          gradle-version: wrapper
          cache-read-only: false
      - name: Warm CC
        run: ./gradlew :account-data-api-integration-tests:test :account-data-api-integration-tests:jacocoTestReport -x spotlessApply -x spotlessCheck -x composeUp
      - name: Save CC
        uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: .gradle/configuration-cache/
          key: ${{ runner.os }}-cc-integration-account-data-${{ hashFiles('**/build.gradle', 'gradle.properties', 'gradle/libs.versions.toml', 'settings.gradle') }}

  run-sonar-analysis:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 #v5.2.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
      - uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v4
        with:
          gradle-version: wrapper
          cache-read-only: false
      - name: Warm CC
        run: ./gradlew --dry-run testCodeCoverageReport sonar -x test -x account-management-integration-tests:test -x spotlessApply -x spotlessCheck
      - name: Save CC
        uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: .gradle/configuration-cache/
          key: ${{ runner.os }}-cc-sonar-${{ hashFiles('**/build.gradle', 'gradle.properties', 'gradle/libs.versions.toml', 'settings.gradle') }}
