AWSTemplateFormatVersion: "2010-09-09"
Transform:
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31

Metadata:
  cfn-lint:
    config:
      ignore_checks:
        - W1028
        - W8003
        - E1011
        - W8001

Description: >
  SAM template for deploying account-data-api

Parameters:
  VpcStackName:
    Description: "The VPC stack name in the account"
    Type: "String"

  CodeSigningConfigArn:
    Type: String
    Description: Asserts that lambdas are signed when deployed.
    Default: "none"

  PermissionsBoundary:
    Description: "The ARN of the permissions boundary to apply when creating IAM roles"
    Type: String
    Default: "nonenonenonenonenone"

  Environment:
    Description: "The name of the environment to deploy to"
    Type: "String"
    AllowedValues:
      - build
      - staging
      - production
      - integration
      - dev

  SubEnvironment:
    Type: String
    Description: >
      When deploying to dev, optionally configure which sub-environment to deploy to
      i.e. authdev1, authdev2. This feature is not available for route-to-live environments
    Default: "none"

  LambdaDeploymentPreference:
    Type: String
    Description: Specifies the configuration to enable gradual Lambda deployments
    Default: AllAtOnce

  LoggingSubscriptionEndpointArn:
    Type: String
    Description: The ARN of the subscription endpoint to send logs to splunk
    Default: "arn:aws:logs:eu-west-2:885513274347:destination:csls_cw_logs_destination_prodpython-2"

Conditions:
  UseSubEnvironment:
    Fn::And:
      - Fn::Equals:
          - !Ref Environment
          - dev
      - Fn::Not:
          - Fn::Equals:
              - !Ref SubEnvironment
              - none

  UseCodeSigning:
    Fn::Not:
      - Fn::Equals:
          - !Ref CodeSigningConfigArn
          - "none"

  UsePermissionsBoundary:
    Fn::Not:
      - Fn::Equals:
          - !Ref PermissionsBoundary
          - "nonenonenonenonenone"

  IsSplunkEnabled:
    Fn::Equals:
      - !FindInMap [EnvironmentConfiguration, !Ref Environment, IsSplunkEnabled]
      - "Yes"

  UseAlarmActions:
    Fn::Equals:
      - !FindInMap [EnvironmentConfiguration, !Ref Environment, UseAlarmActions]
      - "Yes"

Mappings:
  EnvironmentConfiguration:
    authdev1:
      cloudwatchLogRetentionInDays: 1
      authenticatorTableEncryptionKey: arn:aws:kms:eu-west-2:653994557586:key/d41a1b95-0291-4477-93f7-f1428ceef646
    authdev2:
      cloudwatchLogRetentionInDays: 1
      authenticatorTableEncryptionKey: arn:aws:kms:eu-west-2:653994557586:key/88707a9b-53c9-4ad6-ab54-b03b1bf21321
    authdev3:
      cloudwatchLogRetentionInDays: 1
      authenticatorTableEncryptionKey: arn:aws:kms:eu-west-2:653994557586:key/3a47bbdd-4144-4d1a-959f-56b928fcfe3c
    dev:
      cloudwatchLogRetentionInDays: 1
      IsSplunkEnabled: "No"
      dynatraceSecretArn: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceNonProductionVariables
      UseAlarmActions: "No"
      authenticatorTableEncryptionKey: arn:aws:kms:eu-west-2:653994557586:key/c6a2fb5e-c92b-4129-bc0c-d75b2b72bae8
      dataStoreAccountId: 653994557586
    build:
      cloudwatchLogRetentionInDays: 7
      IsSplunkEnabled: "Yes"
      dynatraceSecretArn: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceNonProductionVariables
      UseAlarmActions: "Yes"
      authenticatorTableEncryptionKey: arn:aws:kms:eu-west-2:761723964695:key/3c2113fe-9f53-4bed-a46f-c53f02f6c117
      dataStoreAccountId: 761723964695
    staging:
      cloudwatchLogRetentionInDays: 7
      IsSplunkEnabled: "Yes"
      dynatraceSecretArn: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceNonProductionVariables
      UseAlarmActions: "Yes"
      authenticatorTableEncryptionKey: arn:aws:kms:eu-west-2:758531536632:key/ed6c6a2d-866f-4e2e-9ebd-c499ce9513c6
      dataStoreAccountId: 758531536632
    integration:
      cloudwatchLogRetentionInDays: 30
      IsSplunkEnabled: "Yes"
      dynatraceSecretArn: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceNonProductionVariables
      UseAlarmActions: "Yes"
      authenticatorTableEncryptionKey: arn:aws:kms:eu-west-2:761723964695:key/743b2818-03fd-4414-bfaf-6aa8a4bb4e45
      dataStoreAccountId: 761723964695
    production:
      cloudwatchLogRetentionInDays: 30
      IsSplunkEnabled: "Yes"
      dynatraceSecretArn: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceProductionVariables
      UseAlarmActions: "Yes"
      authenticatorTableEncryptionKey: arn:aws:kms:eu-west-2:172348255554:key/b380ea74-d240-4500-b02b-f5c3d414e34e
      dataStoreAccountId: 172348255554
  LambdaConfiguration:
    passkeys-create:
      RunbookLink: "https://govukverify.atlassian.net/wiki/x/HIHpRQE"
    passkeys-retrieve:
      RunbookLink: "https://govukverify.atlassian.net/wiki/x/HIHpRQE"
    passkeys-update:
      RunbookLink: "https://govukverify.atlassian.net/wiki/x/HIHpRQE"
    passkeys-delete:
      RunbookLink: "https://govukverify.atlassian.net/wiki/x/HIHpRQE"

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Architectures:
      - x86_64
    CodeSigningConfigArn: !If
      - UseCodeSigning
      - !Ref CodeSigningConfigArn
      - !Ref AWS::NoValue
    DeploymentPreference:
      Type: !Ref LambdaDeploymentPreference
      Role: !GetAtt CodeDeployServiceRole.Arn
    Environment:
      Variables:
        ENVIRONMENT:
          !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment]
        AWS_LAMBDA_EXEC_WRAPPER: /opt/dynatrace
        DT_CONNECTION_AUTH_TOKEN: !Sub
          - "{{resolve:secretsmanager:${SecretArn}:SecretString:DT_CONNECTION_AUTH_TOKEN}}"
          - SecretArn:
              !FindInMap [
                EnvironmentConfiguration,
                !Ref Environment,
                dynatraceSecretArn,
              ]
        DT_CONNECTION_BASE_URL: !Sub
          - "{{resolve:secretsmanager:${SecretArn}:SecretString:DT_CONNECTION_BASE_URL}}"
          - SecretArn:
              !FindInMap [
                EnvironmentConfiguration,
                !Ref Environment,
                dynatraceSecretArn,
              ]
        DT_CLUSTER_ID: !Sub
          - "{{resolve:secretsmanager:${SecretArn}:SecretString:DT_CLUSTER_ID}}"
          - SecretArn:
              !FindInMap [
                EnvironmentConfiguration,
                !Ref Environment,
                dynatraceSecretArn,
              ]
        DT_LOG_COLLECTION_AUTH_TOKEN: !Sub
          - "{{resolve:secretsmanager:${SecretArn}:SecretString:DT_LOG_COLLECTION_AUTH_TOKEN}}"
          - SecretArn:
              !FindInMap [
                EnvironmentConfiguration,
                !Ref Environment,
                dynatraceSecretArn,
              ]
        DT_TENANT: !Sub
          - "{{resolve:secretsmanager:${SecretArn}:SecretString:DT_TENANT}}"
          - SecretArn:
              !FindInMap [
                EnvironmentConfiguration,
                !Ref Environment,
                dynatraceSecretArn,
              ]
        DT_OPEN_TELEMETRY_ENABLE_INTEGRATION: "true"
        OTEL_INSTRUMENTATION_AWS_SDK_EXPERIMENTAL_USE_PROPAGATOR_FOR_MESSAGING: "true"
        JAVA_TOOL_OPTIONS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1 '--add-reads=jdk.jfr=ALL-UNNAMED'"
    KmsKeyArn: !GetAtt MainKmsKey.Arn
    Layers:
      - arn:aws:lambda:eu-west-2:216552277552:layer:Dynatrace_OneAgent_1_313_36_20250507-184408_with_collector_java:1
    MemorySize: 1536
    PermissionsBoundary: !If
      - UsePermissionsBoundary
      - !Ref PermissionsBoundary
      - !Ref AWS::NoValue
    Runtime: java17
    Timeout: 30

Resources:
  CodeDeployServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - codedeploy.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSCodeDeployRoleForLambda
      PermissionsBoundary:
        !If [
          UsePermissionsBoundary,
          !Ref PermissionsBoundary,
          !Ref AWS::NoValue,
        ]

  # ----------------
  # Common Resources
  # ----------------

  HttpsEgressSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow egress to external services
      VpcId:
        Fn::ImportValue: !Sub ${VpcStackName}-VpcId
      SecurityGroupEgress:
        - Description: Allow all outgoing HTTPS requests from security group
          CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 443
          ToPort: 443

  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Lambda Security Group permissions ruleset
      VpcId:
        Fn::ImportValue: !Sub ${VpcStackName}-VpcId
      SecurityGroupEgress:
        - Description: Allow outbound traffic to vpc endpoints
          IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          DestinationSecurityGroupId:
            Fn::ImportValue: !Sub ${VpcStackName}-AWSServicesEndpointSecurityGroupId
        - Description: Allow outbound traffic to elasticache
          IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          CidrIp: 10.0.0.0/16
        - DestinationPrefixListId: pl-b3a742da # See https://docs.aws.amazon.com/vpc/latest/userguide/working-with-aws-managed-prefix-lists.html
          Description: Allow outgoing HTTPS requests to AWS DynamoDB route from security group
          IpProtocol: tcp
          FromPort: 443
          ToPort: 443
        # Not sure if we need the below for http requests to S3
        - DestinationPrefixListId: pl-7ca54015 # See https://docs.aws.amazon.com/vpc/latest/userguide/working-with-aws-managed-prefix-lists.html
          Description: Allow outgoing HTTPS requests to AWS S3 route from security group
          IpProtocol: tcp
          FromPort: 443
          ToPort: 443

  MainKmsKey:
    Type: AWS::KMS::Key
    Properties:
      Description: KMS Key that Lambda uses to encrypt and decrypt function's environment variables and logs
      EnableKeyRotation: true
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: kms:*
            Resource: "*"
          - Effect: Allow
            Principal:
              Service: !Sub logs.${AWS::Region}.amazonaws.com
            Action:
              - kms:Encrypt*
              - kms:Decrypt*
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:Describe*
            Resource: "*"
            Condition:
              ArnLike:
                kms:EncryptionContext:aws:logs:arn: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*

  MainKmsKeyAlias:
    Type: "AWS::KMS::Alias"
    Properties:
      AliasName: !Sub
        - "alias/${Env}-auth-account-data-api-main-kms-alias"
        - Env: !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment]
      TargetKeyId: !Ref MainKmsKey

  DynamoAuthenticatorTableReadWriteDeletePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: !Sub
        - "IAM policy for managing read, write and delete permissions to the ${Env}-authenticator table"
        - Env: !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment]
      Path: !Sub
        - /${Env}/ad/
        - Env: !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment]
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowDecryption
            Effect: Allow
            Action:
              - kms:Decrypt
              - kms:Encrypt
              - kms:GenerateDataKey
            Resource:
              - !If
                - UseSubEnvironment
                - !FindInMap [
                    EnvironmentConfiguration,
                    !Ref SubEnvironment,
                    authenticatorTableEncryptionKey,
                  ]
                - !FindInMap [
                    EnvironmentConfiguration,
                    !Ref Environment,
                    authenticatorTableEncryptionKey,
                  ]
          - Sid: AllowReadWriteDelete
            Effect: Allow
            Action:
              - dynamodb:DescribeTable
              - dynamodb:Get*
              - dynamodb:BatchWriteItem
              - dynamodb:UpdateItem
              - dynamodb:PutItem
              - dynamodb:DeleteItem
            Resource:
              - !Sub
                - arn:aws:dynamodb:${AWS::Region}:${DataStoreAccountId}:table/${Env}-authenticator
                - DataStoreAccountId:
                    !FindInMap [
                      EnvironmentConfiguration,
                      !Ref Environment,
                      dataStoreAccountId,
                    ]
                  Env:
                    !If [
                      UseSubEnvironment,
                      !Ref SubEnvironment,
                      !Ref Environment,
                    ]
              - !Sub
                - arn:aws:dynamodb:${AWS::Region}:${DataStoreAccountId}:table/${Env}-authenticator/index/*
                - DataStoreAccountId:
                    !FindInMap [
                      EnvironmentConfiguration,
                      !Ref Environment,
                      dataStoreAccountId,
                    ]
                  Env:
                    !If [
                      UseSubEnvironment,
                      !Ref SubEnvironment,
                      !Ref Environment,
                    ]

  DynamoAuthenticatorTableReadAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: "IAM policy for managing read permissions to the Dynamo Authenticator table"
      Path: !Sub
        - /${Env}/ad/
        - Env: !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment]
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowDecryption
            Effect: Allow
            Action:
              - kms:Decrypt
              - kms:Encrypt
              - kms:GenerateDataKey
            Resource:
              - !If
                - UseSubEnvironment
                - !FindInMap [
                    EnvironmentConfiguration,
                    !Ref SubEnvironment,
                    authenticatorTableEncryptionKey,
                  ]
                - !FindInMap [
                    EnvironmentConfiguration,
                    !Ref Environment,
                    authenticatorTableEncryptionKey,
                  ]
          - Sid: AllowAccessToDynamoTables
            Effect: Allow
            Action:
              - dynamodb:BatchGetItem
              - dynamodb:DescribeTable
              - dynamodb:Get*
            Resource:
              - !Sub
                - arn:aws:dynamodb:${AWS::Region}:${DataStoreAccountId}:table/${Env}-authenticator
                - DataStoreAccountId:
                    !FindInMap [
                      EnvironmentConfiguration,
                      !Ref Environment,
                      dataStoreAccountId,
                    ]
                  Env:
                    !If [
                      UseSubEnvironment,
                      !Ref SubEnvironment,
                      !Ref Environment,
                    ]
              - !Sub
                - arn:aws:dynamodb:${AWS::Region}:${DataStoreAccountId}:table/${Env}-authenticator/index/*
                - DataStoreAccountId:
                    !FindInMap [
                      EnvironmentConfiguration,
                      !Ref Environment,
                      dataStoreAccountId,
                    ]
                  Env:
                    !If [
                      UseSubEnvironment,
                      !Ref SubEnvironment,
                      !Ref Environment,
                    ]

  # ----------------
  # Managed policies
  # ----------------

  LambdaBasicExecutionPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: "IAM policy for Lambda Basic Execution"
      Path: !Sub
        - /${Env}/auth-ad-default/
        - Env: !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment]
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: LoggingFromLambda
            Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource:
              - arn:aws:logs:*:*:*
          - Sid: ManagingVPCConnection
            Effect: Allow
            Action:
              - ec2:DescribeNetworkInterfaces
              - ec2:CreateNetworkInterface
              - ec2:DeleteNetworkInterface
            Resource: "*"
            Condition:
              ArnLikeIfExists:
                ec2:Vpc: !Sub
                  - arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:vpc/${VpcId}
                  - VpcId:
                      Fn::ImportValue: !Sub "${VpcStackName}-VpcId"
          - Sid: XRay
            Effect: Allow
            Action: xray:*
            Resource: "*"
